import { StyleSheet, Platform } from "react-native";

/** Presentation only — extracted verbatim from EventSubmit.tsx. */
export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#f8f9fa",
	},
	scrollContainer: {
		padding: 16,
		paddingBottom: 100,
	},
	formCard: {
		backgroundColor: "white",
		borderRadius: 12,
		...Platform.select({
			ios: {
				shadowColor: "#000",
				shadowOffset: { width: 0, height: 1 },
				shadowOpacity: 0.1,
				shadowRadius: 3,
			},
			android: {
				elevation: 2,
			},
		}),
		marginBottom: 16,
		overflow: "hidden",
	},
	sectionContainer: {
		padding: 16,
		borderBottomWidth: 1,
		borderBottomColor: "#f0f0f0",
	},
	sectionTitle: {
		fontSize: 18,
		fontWeight: "700",
		color: "#333",
		marginBottom: 16,
	},
	inputContainer: {
		marginBottom: 16,
	},
	timeContainer: {
		flexDirection: "column",
	},
	timeField: {
		flex: 1,
	},
	label: {
		fontSize: 15,
		marginBottom: 8,
		color: "#555",
		fontWeight: "500",
	},
	input: {
		height: 50,
		borderColor: "#e0e0e0",
		borderWidth: 1,
		borderRadius: 8,
		paddingHorizontal: 15,
		fontSize: 16,
		backgroundColor: "white",
		color: "#333",
	},
	dateButton: {
		backgroundColor: "white",
		padding: 15,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#e0e0e0",
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	dateButtonText: {
		fontSize: 16,
		color: "#333",
	},
	checkboxWrapper: {
		marginBottom: 16,
	},
	checkboxContainer: {
		flexDirection: "row",
		alignItems: "center",
	},
	checkbox: {
		marginRight: 8,
	},
	checkboxLabel: {
		fontSize: 15,
		color: "#333",
		fontWeight: "500",
	},
	dropdown: {
		borderColor: "#e0e0e0",
		borderWidth: 1,
		borderRadius: 8,
		backgroundColor: "white",
		minHeight: 50,
	},
	dropdownList: {
		borderColor: "#e0e0e0",
		borderWidth: 1,
		borderRadius: 8,
		backgroundColor: "white",
		marginTop: 1,
		position: "relative",
		top: 0,
	},
	dropdownItem: {
		borderBottomWidth: 1,
		borderBottomColor: "#f0f0f0",
		minHeight: 40,
		justifyContent: "center",
	},
	notesInput: {
		minHeight: 100,
		borderColor: "#e0e0e0",
		borderWidth: 1,
		borderRadius: 8,
		paddingHorizontal: 15,
		paddingTop: 12,
		paddingBottom: 12,
		fontSize: 16,
		backgroundColor: "white",
		color: "#333",
		textAlignVertical: "top",
	},
	attachmentsContainer: {
		marginTop: 8,
	},
	actionButtonsContainer: {
		marginTop: 8,
		marginBottom: 24,
	},
	submitButton: {
		backgroundColor: "#3d7eea",
		padding: 15,
		borderRadius: 8,
		alignItems: "center",
		flexDirection: "row",
		justifyContent: "center",
		marginBottom: 12,
	},
	submitButtonText: {
		color: "#fff",
		fontSize: 17,
		fontWeight: "600",
		marginLeft: 8,
	},
	deleteButton: {
		backgroundColor: "#e74c3c",
		padding: 15,
		borderRadius: 8,
		alignItems: "center",
		flexDirection: "row",
		justifyContent: "center",
	},
	helperText: {
		fontSize: 14,
		color: "#666",
		marginBottom: 12,
	},
	emptyPackagesContainer: {
		padding: 20,
		backgroundColor: "#f9f9f9",
		borderRadius: 8,
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 1,
		borderColor: "#eee",
		borderStyle: "dashed",
	},
	emptyPackagesText: {
		color: "#999",
		fontSize: 16,
	},
	packagesContainer: {
		marginTop: 8,
	},
	packageItem: {
		backgroundColor: "#f9f9f9",
		borderRadius: 8,
		marginBottom: 12,
		borderWidth: 1,
		borderColor: "#eee",
		overflow: "hidden",
	},
	packageItemSelected: {
		backgroundColor: "#eaf4ff",
		borderColor: "#3d7eea",
	},
	packageItemContent: {
		padding: 12,
	},
	packageItemHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 8,
	},
	packageItemTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "#333",
		flex: 1,
	},
	packageItemDescription: {
		fontSize: 14,
		color: "#666",
		marginBottom: 8,
	},
	packageItemStats: {
		fontSize: 14,
		color: "#888",
	},
	selectedPackagesContainer: {
		marginTop: 16,
		borderTopWidth: 1,
		borderTopColor: "#eee",
		paddingTop: 16,
	},
	selectedPackagesTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "#333",
		marginBottom: 12,
	},
	removePackageButton: {
		padding: 4,
	},
	emptyLabelsContainer: {
		padding: 15,
		backgroundColor: "#f9f9f9",
		borderRadius: 8,
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 1,
		borderColor: "#eee",
		borderStyle: "dashed",
		marginVertical: 8,
	},
	emptyLabelsText: {
		color: "#999",
		fontSize: 16,
	},
	labelSelectorContainer: {
		marginTop: 8,
		marginBottom: 8,
	},
	labelsGrid: {
		flexDirection: "row",
		flexWrap: "wrap",
	},
	labelOption: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 12,
		paddingVertical: 8,
		borderRadius: 16,
		marginRight: 8,
		marginBottom: 8,
		backgroundColor: "#f5f5f5",
		borderWidth: 1,
		borderColor: "#e0e0e0",
		minHeight: 36,
	},
	labelOptionSelected: {
		backgroundColor: "#eaf4ff",
		borderColor: "#3d7eea",
	},
	labelColor: {
		width: 18,
		height: 18,
		borderRadius: 9,
		marginRight: 8,
	},
	labelColorNone: {
		width: 18,
		height: 18,
		borderRadius: 9,
		marginRight: 8,
		backgroundColor: "#f0f0f0",
		alignItems: "center",
		justifyContent: "center",
	},
	labelOptionText: {
		fontSize: 14,
		color: "#333",
	},
	audienceHint: {
		fontSize: 13,
		color: "#777",
		lineHeight: 18,
		marginBottom: 10,
	},
	audienceEmpty: {
		fontSize: 14,
		color: "#999",
		paddingVertical: 8,
	},
	audienceSectionTitle: {
		fontSize: 12,
		fontWeight: "700",
		color: "#888",
		textTransform: "uppercase",
		marginTop: 14,
		marginBottom: 2,
	},
	audienceSearch: {
		backgroundColor: "#f4f4f6",
		borderRadius: 8,
		paddingHorizontal: 12,
		paddingVertical: 9,
		fontSize: 14,
		color: "#222",
		marginTop: 6,
		marginBottom: 4,
	},
	audienceRow: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 10,
	},
	audienceLabel: {
		fontSize: 15,
		color: "#333",
		marginLeft: 10,
		flex: 1,
	},
	selectedLabelContainer: {
		marginTop: 16,
		paddingTop: 8,
	},
	selectedLabel: {
		paddingHorizontal: 12,
		paddingVertical: 6,
		borderRadius: 16,
		alignSelf: "flex-start",
		marginTop: 4,
	},
	selectedLabelText: {
		color: "white",
		fontSize: 14,
		fontWeight: "500",
		textShadowColor: "rgba(0, 0, 0, 0.3)",
		textShadowOffset: { width: 0, height: 1 },
		textShadowRadius: 2,
	},
});
