/*
 * Vendors the Ionicons the portal uses into a single TypeScript module.
 *
 * The mobile app renders Ionicons from a TTF via @expo/vector-icons. A font is
 * the wrong shape for the web here — it would mean shipping a 200KB typeface to
 * draw forty glyphs — so the SVG source of the SAME icon set is inlined instead.
 * Same artwork, same visual language, no runtime dependency.
 *
 * The `ionicons` package is a devDependency: this script reads from it at build
 * time and the generated module is committed, so a production install does not
 * need it.
 *
 *   node scripts/build-icons.mjs
 *
 * Icon names come from two places: every glyph the app currently references
 * (grep `name="..."` under src/components, src/screens, src/navigation), plus
 * the desktop-only additions the portal needs — sorting, filtering, exporting,
 * the sidebar.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SVG_DIR = resolve(here, "../node_modules/ionicons/dist/svg");
const OUT = resolve(here, "../src/ui/icons.generated.ts");

/** Glyphs the mobile app already uses. Keep in sync when a screen adds one. */
const FROM_APP = [
	"add",
	"add-circle-outline",
	"alert-circle",
	"alert-circle-outline",
	"arrow-back",
	"arrow-forward",
	"calendar",
	"calendar-outline",
	"camera-outline",
	"checkmark",
	"checkmark-circle",
	"checkmark-circle-outline",
	"chevron-back",
	"chevron-down",
	"chevron-forward",
	"chevron-up",
	"close",
	"close-circle",
	"cloud-upload-outline",
	"color-palette-outline",
	"document-outline",
	"document-text-outline",
	"ellipsis-horizontal",
	"eye-off-outline",
	"eye-outline",
	"help-circle",
	"help-circle-outline",
	"information-circle",
	"information-circle-outline",
	"list",
	"location-outline",
	"lock-closed-outline",
	"log-out-outline",
	"mail-outline",
	"people",
	"people-outline",
	"person-circle-outline",
	"person-outline",
	"pricetag-outline",
	"refresh",
	"search",
	"settings",
	"settings-outline",
	"time",
	"time-outline",
	"trash-outline",
	"warning",
];

/** Desktop affordances the phone has no room for. */
const FOR_PORTAL = [
	"albums-outline",
	"apps-outline",
	"arrow-down",
	"arrow-up",
	"bar-chart-outline",
	"business-outline",
	"calculator-outline",
	"copy-outline",
	"download-outline",
	"ellipse-outline",
	"filter",
	"funnel-outline",
	"grid-outline",
	"key-outline",
	"link-outline",
	"moon-outline",
	"open-outline",
	"options-outline",
	"pencil",
	"print-outline",
	"resize",
	"save-outline",
	"share-outline",
	"sunny-outline",
	"swap-vertical",
];

const NAMES = [...new Set([...FROM_APP, ...FOR_PORTAL])].sort();

/** Everything between <svg …> and </svg>, verbatim. */
function innerSvg(name) {
	const raw = readFileSync(resolve(SVG_DIR, `${name}.svg`), "utf8");
	const match = raw.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
	if (!match) throw new Error(`Could not parse ${name}.svg`);
	return match[1].replace(/\s+/g, " ").replace(/> </g, "><").trim();
}

const missing = [];
const entries = [];

for (const name of NAMES) {
	try {
		entries.push([name, innerSvg(name)]);
	} catch {
		missing.push(name);
	}
}

if (missing.length) {
	console.error(
		`Not found in the ionicons package:\n  ${missing.join("\n  ")}`,
	);
	process.exit(1);
}

const body = entries
	.map(([name, svg]) => `\t"${name}": '${svg.replace(/'/g, "\\'")}',`)
	.join("\n");

const output = `/*
 * GENERATED by scripts/build-icons.mjs — do not edit by hand.
 *
 * Inner SVG markup for the Ionicons the portal uses, on the set's native
 * 512x512 grid. Regenerate with: node scripts/build-icons.mjs
 */

export const ICONS: Record<string, string> = {
${body}
};

export type IconName = keyof typeof ICONS;
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, output);
console.log(`Wrote ${entries.length} icons to ${OUT}`);
