import { StyleSheet, Platform } from "react-native";

/** Presentation only — extracted verbatim from AvailabilityPage.tsx. */
export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#F9FAFB",
	},
	header: {
		padding: 16,
		paddingTop: 12,
		paddingBottom: 8,
		alignItems: "center",
		backgroundColor: "#fff",
		...Platform.select({
			ios: {
				shadowColor: "#000",
				shadowOffset: { width: 0, height: 1 },
				shadowOpacity: 0.1,
				shadowRadius: 2,
			},
			android: {
				elevation: 2,
			},
		}),
	},
	title: {
		fontSize: 20,
		fontWeight: "700",
		color: "#1F2937",
		letterSpacing: 0.5,
	},
	tabOuterContainer: {
		backgroundColor: "#fff",
		paddingHorizontal: 16,
		marginBottom: 16,
		...Platform.select({
			ios: {
				shadowColor: "#000",
				shadowOffset: { width: 0, height: 1 },
				shadowOpacity: 0.05,
				shadowRadius: 1,
			},
			android: {
				elevation: 1,
			},
		}),
	},
	tabContainer: {
		flexDirection: "row",
		position: "relative",
		height: 48,
	},
	tab: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	activeTab: {},
	tabText: {
		fontSize: 14,
		fontWeight: "600",
		color: "#6B7280",
	},
	activeTabText: {
		color: "#4A90E2",
		fontWeight: "700",
	},
	tabIndicator: {
		position: "absolute",
		bottom: 0,
		height: 3,
		backgroundColor: "#4A90E2",
		borderRadius: 3,
	},
	eventList: {
		paddingHorizontal: 16,
		paddingBottom: 20,
	},
	eventCard: {
		backgroundColor: "#FFFFFF",
		borderRadius: 12,
		padding: 16,
		marginBottom: 12,
		...Platform.select({
			ios: {
				shadowColor: "#000",
				shadowOffset: { width: 0, height: 2 },
				shadowOpacity: 0.06,
				shadowRadius: 4,
			},
			android: {
				elevation: 2,
			},
		}),
	},
	eventHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
	},
	dateLocationContainer: {
		flex: 1,
	},
	eventDate: {
		fontSize: 16,
		fontWeight: "700",
		color: "#1F2937",
		marginBottom: 4,
	},
	groupBadgeRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		marginTop: 6,
	},
	groupBadge: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#efeaff",
		borderRadius: 10,
		paddingHorizontal: 8,
		paddingVertical: 3,
		marginRight: 6,
		marginBottom: 4,
		maxWidth: 160,
	},
	groupBadgeText: {
		fontSize: 11,
		fontWeight: "600",
		color: "#5a3ec8",
		marginLeft: 4,
		flexShrink: 1,
	},
	eventTitle: {
		fontSize: 18,
		fontWeight: "700",
		color: "#1F2937",
		marginBottom: 4,
	},
	eventTime: {
		fontSize: 14,
		color: "#4B5563",
		marginBottom: 4,
	},
	locationContainer: {
		flexDirection: "row",
		alignItems: "center",
	},
	eventLocation: {
		fontSize: 14,
		color: "#6B7280",
		marginLeft: 4,
	},
	statusBadge: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 12,
		marginLeft: 8,
	},
	statusIcon: {
		marginRight: 4,
	},
	statusBadgeText: {
		fontSize: 12,
		fontWeight: "600",
		color: "#FFFFFF",
	},
	buttonContainer: {
		flexDirection: "row",
		marginTop: 16,
		justifyContent: "flex-end",
	},
	confirmButton: {
		backgroundColor: "#4ADE80",
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 8,
		paddingHorizontal: 16,
		borderRadius: 8,
		marginLeft: 12,
	},
	declineButton: {
		backgroundColor: "#EF4444",
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 8,
		paddingHorizontal: 16,
		borderRadius: 8,
	},
	undeclineButton: {
		backgroundColor: "#6366F1", // Indigo color
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 8,
		paddingHorizontal: 16,
		borderRadius: 8,
	},
	buttonText: {
		color: "#FFFFFF",
		fontWeight: "600",
		fontSize: 14,
		marginLeft: 6,
	},
	loadingContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	loadingText: {
		marginTop: 12,
		fontSize: 16,
		color: "#6B7280",
	},
	emptyStateContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingHorizontal: 32,
		paddingVertical: 64,
	},
	emptyStateTitle: {
		fontSize: 18,
		fontWeight: "700",
		color: "#374151",
		marginTop: 16,
	},
	emptyStateDescription: {
		fontSize: 14,
		color: "#6B7280",
		textAlign: "center",
		marginTop: 8,
	},
	adminButton: {
		position: "absolute",
		right: 16,
		top: 12,
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#F3F4F6",
		paddingHorizontal: 12,
		paddingVertical: 6,
		borderRadius: 20,
	},
	adminButtonText: {
		fontSize: 12,
		fontWeight: "600",
		color: "#4A90E2",
		marginLeft: 4,
	},
	modalOverlay: {
		flex: 1,
		backgroundColor: "rgba(0, 0, 0, 0.5)",
		justifyContent: "center",
		alignItems: "center",
	},
	modalContent: {
		backgroundColor: "#FFFFFF",
		borderRadius: 16,
		width: "90%",
		maxHeight: "80%",
		overflow: "hidden",
	},
	modalHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		padding: 20,
		borderBottomWidth: 1,
		borderBottomColor: "#E5E7EB",
	},
	modalTitle: {
		fontSize: 18,
		fontWeight: "700",
		color: "#1F2937",
	},
	closeButton: {
		padding: 4,
	},
	modalBody: {
		padding: 20,
	},
	modalDescription: {
		fontSize: 14,
		color: "#6B7280",
		marginBottom: 20,
		lineHeight: 20,
	},
	timeInputContainer: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		marginBottom: 20,
	},
	inputGroup: {
		alignItems: "center",
	},
	inputLabel: {
		fontSize: 12,
		fontWeight: "600",
		color: "#6B7280",
		marginBottom: 8,
	},
	timeInput: {
		borderWidth: 2,
		borderColor: "#E5E7EB",
		borderRadius: 8,
		padding: 12,
		fontSize: 18,
		fontWeight: "600",
		textAlign: "center",
		width: 80,
		backgroundColor: "#F9FAFB",
	},
	timeSeparator: {
		fontSize: 24,
		fontWeight: "bold",
		color: "#6B7280",
		marginHorizontal: 16,
	},
	previewText: {
		fontSize: 13,
		color: "#4B5563",
		textAlign: "center",
		backgroundColor: "#F3F4F6",
		padding: 12,
		borderRadius: 8,
	},
	modalFooter: {
		flexDirection: "row",
		padding: 20,
		borderTopWidth: 1,
		borderTopColor: "#E5E7EB",
	},
	cancelButton: {
		flex: 1,
		paddingVertical: 12,
		marginRight: 8,
		backgroundColor: "#F3F4F6",
		borderRadius: 8,
		alignItems: "center",
	},
	cancelButtonText: {
		fontSize: 16,
		fontWeight: "600",
		color: "#6B7280",
	},
	saveButton: {
		flex: 1,
		paddingVertical: 12,
		marginLeft: 8,
		backgroundColor: "#4A90E2",
		borderRadius: 8,
		alignItems: "center",
	},
	saveButtonText: {
		fontSize: 16,
		fontWeight: "600",
		color: "#FFFFFF",
	},
	toggleContainer: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		paddingVertical: 16,
		paddingHorizontal: 16,
		backgroundColor: "#F9FAFB",
		borderRadius: 12,
		marginBottom: 24,
	},
	toggleLabelContainer: {
		flex: 1,
		marginRight: 16,
	},
	toggleLabel: {
		fontSize: 16,
		fontWeight: "600",
		color: "#1F2937",
		marginBottom: 2,
	},
	toggleSubLabel: {
		fontSize: 13,
		color: "#6B7280",
	},
	sectionLabel: {
		fontSize: 14,
		fontWeight: "600",
		color: "#374151",
		marginBottom: 12,
	},
	disabledText: {
		fontSize: 14,
		color: "#6B7280",
		textAlign: "center",
		backgroundColor: "#FEF3C7",
		padding: 16,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#F59E0B",
		marginTop: 16,
	},
	// New styles for admin event details modal
	eventDetailsContainer: {
		marginBottom: 24,
	},
	eventDetailsTitle: {
		fontSize: 18,
		fontWeight: "700",
		color: "#1F2937",
		marginBottom: 8,
	},
	eventDetailsDate: {
		fontSize: 14,
		color: "#6B7280",
		marginBottom: 4,
	},
	eventDetailsLocation: {
		fontSize: 14,
		color: "#6B7280",
		marginBottom: 16,
	},
	workerDetailsContainer: {
		backgroundColor: "#F9FAFB",
		borderRadius: 12,
		padding: 16,
	},
	workerDetailsTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "#374151",
		marginBottom: 12,
	},
	workerGroup: {
		marginBottom: 16,
	},
	workerGroupTitle: {
		fontSize: 14,
		fontWeight: "600",
		color: "#1F2937",
		marginBottom: 8,
	},
	workerCard: {
		backgroundColor: "#FFFFFF",
		borderRadius: 8,
		padding: 12,
		marginBottom: 8,
		...Platform.select({
			ios: {
				shadowColor: "#000",
				shadowOffset: { width: 0, height: 2 },
				shadowOpacity: 0.05,
				shadowRadius: 4,
			},
			android: {
				elevation: 2,
			},
		}),
	},
	workerName: {
		fontSize: 14,
		fontWeight: "500",
		color: "#374151",
		flex: 1,
	},
	workerStatus: {
		fontSize: 13,
		color: "#6B7280",
		marginTop: 4,
	},
	adminModalContent: {
		backgroundColor: "#FFFFFF",
		borderRadius: 16,
		width: "95%",
		maxHeight: "90%",
		overflow: "hidden",
	},
	adminModalBody: {
		maxHeight: 400,
	},
	eventInfoHeader: {
		padding: 20,
		backgroundColor: "#F9FAFB",
		borderBottomWidth: 1,
		borderBottomColor: "#E5E7EB",
	},
	eventInfoTitle: {
		fontSize: 18,
		fontWeight: "700",
		color: "#1F2937",
		marginBottom: 4,
	},
	eventInfoDate: {
		fontSize: 14,
		color: "#6B7280",
		marginBottom: 2,
	},
	eventInfoLocation: {
		fontSize: 14,
		color: "#6B7280",
	},
	workerSection: {
		paddingHorizontal: 20,
		paddingVertical: 16,
		borderBottomWidth: 1,
		borderBottomColor: "#F3F4F6",
	},
	sectionHeaderRow: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 12,
	},
	sectionTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "#374151",
		marginLeft: 8,
	},
	workerItem: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		paddingVertical: 8,
		paddingHorizontal: 12,
		backgroundColor: "#F9FAFB",
		borderRadius: 8,
		marginBottom: 8,
	},
	workerItemActions: {
		flexDirection: "row",
		gap: 8,
	},
	adminConfirmBtn: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#4ADE80",
		paddingVertical: 4,
		paddingHorizontal: 10,
		borderRadius: 6,
	},
	adminDeclineBtn: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#EF4444",
		paddingVertical: 4,
		paddingHorizontal: 10,
		borderRadius: 6,
	},
	adminBtnText: {
		color: "#FFFFFF",
		fontSize: 12,
		fontWeight: "600",
		marginLeft: 4,
	},
	emptyText: {
		fontSize: 14,
		color: "#9CA3AF",
		fontStyle: "italic",
		textAlign: "center",
		paddingVertical: 12,
	},
	adminModalFooter: {
		flexDirection: "row",
		padding: 20,
		borderTopWidth: 1,
		borderTopColor: "#E5E7EB",
		gap: 12, // Add spacing between buttons
	},
	closeModalButton: {
		flex: 1,
		paddingVertical: 12,
		backgroundColor: "#6B7280",
		borderRadius: 8,
		alignItems: "center",
	},
	closeModalButtonText: {
		fontSize: 16,
		fontWeight: "600",
		color: "#FFFFFF",
	},
	openEventButton: {
		flex: 1,
		paddingVertical: 12,
		backgroundColor: "#4A90E2",
		borderRadius: 8,
		alignItems: "center",
	},
	openEventButtonText: {
		fontSize: 16,
		fontWeight: "600",
		color: "#FFFFFF",
	},
});
