import { StyleSheet } from "react-native";
import { Theme } from "../../theme";

/** Presentation only — extracted verbatim from TimeEntryDetails.tsx. */
export const timeEntryDetailStyles = (theme: Theme) =>
	StyleSheet.create({
		container: {
			flex: 1,
			backgroundColor: theme.colors.surfaceSunken,
		},
		loadingContainer: {
			justifyContent: "center",
			alignItems: "center",
		},
		loadingText: {
			marginTop: 16,
			fontSize: 16,
			color: theme.colors.textSecondary,
		},
		header: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			paddingHorizontal: 16,
			paddingVertical: 12,
			backgroundColor: theme.colors.surface,
			borderBottomWidth: 1,
			borderBottomColor: theme.colors.border,
		},
		backButton: {
			padding: 4,
		},
		headerTitle: {
			fontSize: 18,
			fontWeight: "600",
			flex: 1,
			textAlign: "center",
		},
		scrollContainer: {
			flex: 1,
		},
		// Bottom sheet styles
		sheetBackground: {
			backgroundColor: theme.colors.surface,
		},
		sheetIndicator: {
			backgroundColor: theme.colors.border,
			width: 40,
			height: 4,
		},
		sheetHeader: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			paddingHorizontal: 20,
			paddingVertical: 16,
			borderBottomWidth: 1,
			borderBottomColor: theme.colors.border,
		},
		sheetContent: {
			padding: 20,
			paddingBottom: 40,
		},
		summaryCard: {
			margin: 16,
			padding: 16,
			backgroundColor: theme.colors.surface,
			borderRadius: 12,
			shadowColor: theme.colors.shadow,
			shadowOffset: { width: 0, height: 2 },
			shadowOpacity: 0.1,
			shadowRadius: 4,
			elevation: 2,
		},
		summaryRow: {
			flexDirection: "row",
			justifyContent: "space-between",
			marginBottom: 12,
			alignItems: "center",
		},
		totalSummaryRow: {
			marginTop: 8,
		},
		summaryLabel: {
			fontSize: 16,
			color: theme.colors.textSecondary,
			fontWeight: "500",
		},
		summaryValue: {
			fontSize: 14,
			color: theme.colors.text,
			fontWeight: "500",
			textAlign: "right",
			flex: 1,
		},
		totalValue: {
			fontWeight: "600",
			color: theme.colors.accent,
		},
		statusContainer: {
			flexDirection: "row",
			justifyContent: "flex-end",
		},
		statusBadge: {
			paddingHorizontal: 8,
			paddingVertical: 3,
			borderRadius: 12,
			backgroundColor: theme.colors.border,
		},
		statusText: {
			fontSize: 12,
			fontWeight: "600",
			color: theme.colors.textSecondary,
		},
		managerActionsCard: {
			margin: 16,
			marginTop: 0,
			padding: 16,
			backgroundColor: theme.colors.surface,
			borderRadius: 12,
			shadowColor: theme.colors.shadow,
			shadowOffset: { width: 0, height: 2 },
			shadowOpacity: 0.1,
			shadowRadius: 4,
			elevation: 2,
		},
		selectAllRow: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			marginBottom: 16,
		},
		selectAllButton: {
			flexDirection: "row",
			alignItems: "center",
		},
		selectAllText: {
			marginLeft: 8,
			fontSize: 16,
			color: theme.colors.accent,
			fontWeight: "500",
		},
		selectedCountText: {
			fontSize: 14,
			color: theme.colors.textSecondary,
		},
		managerButtonRow: {
			flexDirection: "row",
			justifyContent: "space-between",
			gap: 10,
		},
		managerActionButton: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			paddingVertical: 12,
			paddingHorizontal: 16,
			borderRadius: 8,
			flex: 1,
		},
		approveButton: {
			backgroundColor: theme.colors.success,
		},
		emailButton: {
			backgroundColor: theme.colors.accent,
		},
		rejectButton: {
			backgroundColor: theme.colors.danger,
		},
		disabledButton: {
			opacity: 0.5,
		},
		buttonText: {
			color: theme.colors.surface,
			fontWeight: "600",
			marginLeft: 8,
		},
		timeEntryCard: {
			marginHorizontal: 16,
			marginBottom: 16,
			backgroundColor: theme.colors.surface,
			borderRadius: 12,
			shadowColor: theme.colors.shadow,
			shadowOffset: { width: 0, height: 1 },
			shadowOpacity: 0.1,
			shadowRadius: 2,
			elevation: 2,
			overflow: "hidden",
		},
		timeEntryHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			padding: 16,
			borderBottomWidth: 1,
			borderBottomColor: theme.colors.border,
		},
		headerLeftSection: {
			flexDirection: "row",
			alignItems: "center",
			flex: 1,
		},
		selectionCheckbox: {
			marginRight: 12,
		},
		dateTimeText: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.text,
		},
		timeEntryDetails: {
			padding: 16,
		},
		detailRow: {
			flexDirection: "row",
			marginBottom: 8,
		},
		detailLabel: {
			fontSize: 15,
			color: theme.colors.textSecondary,
			width: 80,
		},
		detailValue: {
			fontSize: 15,
			color: theme.colors.text,
			flex: 1,
		},
		connectedEventsSection: {
			marginTop: 16,
		},
		sectionTitle: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.text,
			marginBottom: 8,
		},
		connectedEventContainer: {
			marginBottom: 16,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			overflow: "hidden",
		},
		connectedEventItem: {
			flexDirection: "row",
			alignItems: "center",
			paddingVertical: 10,
			paddingHorizontal: 12,
			backgroundColor: theme.colors.surfaceSunken,
			borderBottomColor: theme.colors.border,
		},
		eventFormResponsesSection: {
			padding: 12,
			backgroundColor: theme.colors.surface,
		},
		eventFormTitle: {
			fontSize: 14,
			fontWeight: "500",
			color: theme.colors.textSecondary,
			marginBottom: 8,
		},
		notesSection: {
			marginTop: 16,
		},
		notesText: {
			fontSize: 15,
			color: theme.colors.text,
			lineHeight: 22,
		},
		formResponsesSection: {
			marginTop: 16,
			borderTopWidth: 1,
			borderTopColor: theme.colors.border,
			paddingTop: 16,
		},
		formResponseItem: {
			marginBottom: 12,
		},
		formFieldLabel: {
			fontSize: 14,
			color: theme.colors.textSecondary,
			marginBottom: 4,
		},
		formFieldValue: {
			fontSize: 15,
			color: theme.colors.text,
		},
		multiplierValue: {
			fontSize: 14,
			color: theme.colors.accent,
		},
		editHistorySection: {
			marginTop: 16,
			paddingTop: 12,
			borderTopWidth: 1,
			borderTopColor: theme.colors.border,
		},
		editHistoryItem: {
			marginBottom: 12,
			padding: 10,
			backgroundColor: theme.colors.accentSubtle,
			borderRadius: 6,
		},
		editTimestamp: {
			fontSize: 13,
			color: theme.colors.textSecondary,
			marginBottom: 4,
		},
		editSummary: {
			fontSize: 14,
			color: theme.colors.text,
			fontWeight: "500",
		},
		entryActions: {
			marginTop: 16,
			flexDirection: "row",
			justifyContent: "flex-end",
		},
		editButton: {
			flexDirection: "row",
			alignItems: "center",
			paddingVertical: 8,
			paddingHorizontal: 12,
			borderRadius: 6,
			backgroundColor: theme.colors.accentSubtle,
		},
		editButtonText: {
			marginLeft: 6,
			fontSize: 14,
			fontWeight: "500",
			color: theme.colors.accent,
		},
		modal: {
			margin: 0,
			justifyContent: "flex-end",
		},
		modalContent: {
			backgroundColor: theme.colors.surface,
			borderTopLeftRadius: 12,
			borderTopRightRadius: 12,
			padding: 20,
		},
		modalTitle: {
			fontSize: 18,
			fontWeight: "600",
			color: theme.colors.text,
			marginBottom: 4,
			textAlign: "center",
		},
		modalForm: {
			marginBottom: 20,
		},
		modalLabel: {
			fontSize: 15,
			fontWeight: "500",
			color: theme.colors.text,
			marginBottom: 8,
		},
		modalInput: {
			height: 44,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			paddingHorizontal: 12,
			fontSize: 16,
			marginBottom: 16,
		},
		modalTextArea: {
			height: 100,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			paddingHorizontal: 12,
			paddingTop: 12,
			paddingBottom: 12,
			fontSize: 16,
			marginBottom: 16,
			textAlignVertical: "top",
		},
		modalButtons: {
			flexDirection: "row",
			justifyContent: "space-between",
		},
		modalButton: {
			paddingVertical: 12,
			borderRadius: 8,
			alignItems: "center",
			justifyContent: "center",
			flex: 1,
		},
		modalCancelButton: {
			backgroundColor: theme.colors.surfaceSunken,
			marginRight: 8,
		},
		modalSaveButton: {
			backgroundColor: theme.colors.accent,
			marginLeft: 8,
		},
		modalCancelButtonText: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.textSecondary,
		},
		modalSaveButtonText: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.surface,
		},
		exportOptionRow: {
			marginBottom: 20,
		},
		exportOptions: {
			flexDirection: "row",
			marginTop: 8,
		},
		exportOption: {
			flex: 1,
			paddingVertical: 10,
			alignItems: "center",
			borderWidth: 1,
			borderColor: theme.colors.border,
			marginHorizontal: 4,
			borderRadius: 6,
		},
		selectedExportOption: {
			borderColor: theme.colors.accent,
			backgroundColor: theme.colors.accentSubtle,
		},
		exportOptionText: {
			fontSize: 15,
			color: theme.colors.textSecondary,
		},
		selectedExportOptionText: {
			color: theme.colors.accent,
			fontWeight: "500",
		},
		fileResponseGrid: {
			flexDirection: "row",
			flexWrap: "wrap",
			gap: 10,
			marginTop: 8,
		},
		fileResponseItem: {
			width: 80,
			height: 80,
			borderRadius: 8,
			overflow: "hidden",
			borderWidth: 1,
			borderColor: theme.colors.border,
		},
		fileResponseImage: {
			width: "100%",
			height: "100%",
			resizeMode: "cover",
		},
		videoOverlay: {
			...StyleSheet.absoluteFillObject,
			backgroundColor: "rgba(0,0,0,0.3)",
			justifyContent: "center",
			alignItems: "center",
		},
		fileResponseDoc: {
			width: "100%",
			height: "100%",
			justifyContent: "center",
			alignItems: "center",
			backgroundColor: theme.colors.surfaceSunken,
		},
		fileResponseVideo: {
			width: "100%",
			height: "100%",
			position: "relative",
		},
		fileResponseName: {
			fontSize: 10,
			color: theme.colors.textSecondary,
			textAlign: "center",
			paddingHorizontal: 4,
			marginTop: 4,
		},
		eventTitle: {
			fontSize: 15,
			fontWeight: "500",
			color: theme.colors.text,
			marginLeft: 8,
		},
	});
