import { StyleSheet } from "react-native";

/** Presentation only — extracted verbatim from TimeEntryDetails.tsx. */
export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#f7f7f7",
	},
	loadingContainer: {
		justifyContent: "center",
		alignItems: "center",
	},
	loadingText: {
		marginTop: 16,
		fontSize: 16,
		color: "#666",
	},
	header: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 16,
		paddingVertical: 12,
		backgroundColor: "#fff",
		borderBottomWidth: 1,
		borderBottomColor: "#e1e4e8",
	},
	backButton: {
		padding: 4,
	},
	headerTitle: {
		fontSize: 18,
		fontWeight: "600",
		flex: 1,
		textAlign: "center",
	},
	scrollContainer: {
		flex: 1,
	},
	// Bottom sheet styles
	sheetBackground: {
		backgroundColor: "white",
	},
	sheetIndicator: {
		backgroundColor: "#ccc",
		width: 40,
		height: 4,
	},
	sheetHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 20,
		paddingVertical: 16,
		borderBottomWidth: 1,
		borderBottomColor: "#eaeaea",
	},
	sheetContent: {
		padding: 20,
		paddingBottom: 40,
	},
	summaryCard: {
		margin: 16,
		padding: 16,
		backgroundColor: "#fff",
		borderRadius: 12,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 2,
	},
	summaryRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginBottom: 12,
		alignItems: "center",
	},
	totalSummaryRow: {
		marginTop: 8,
	},
	summaryLabel: {
		fontSize: 16,
		color: "#666",
		fontWeight: "500",
	},
	summaryValue: {
		fontSize: 14,
		color: "#333",
		fontWeight: "500",
		textAlign: "right",
		flex: 1,
	},
	totalValue: {
		fontWeight: "600",
		color: "#007AFF",
	},
	statusContainer: {
		flexDirection: "row",
		justifyContent: "flex-end",
	},
	statusBadge: {
		paddingHorizontal: 8,
		paddingVertical: 3,
		borderRadius: 12,
		backgroundColor: "#e0e0e0",
	},
	statusText: {
		fontSize: 12,
		fontWeight: "600",
		color: "#555",
	},
	managerActionsCard: {
		margin: 16,
		marginTop: 0,
		padding: 16,
		backgroundColor: "#fff",
		borderRadius: 12,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 2,
	},
	selectAllRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 16,
	},
	selectAllButton: {
		flexDirection: "row",
		alignItems: "center",
	},
	selectAllText: {
		marginLeft: 8,
		fontSize: 16,
		color: "#007AFF",
		fontWeight: "500",
	},
	selectedCountText: {
		fontSize: 14,
		color: "#666",
	},
	managerButtonRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		gap: 10,
	},
	managerActionButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderRadius: 8,
		flex: 1,
	},
	approveButton: {
		backgroundColor: "#34C759",
	},
	emailButton: {
		backgroundColor: "#007AFF",
	},
	rejectButton: {
		backgroundColor: "#FF3B30",
	},
	disabledButton: {
		opacity: 0.5,
	},
	buttonText: {
		color: "#fff",
		fontWeight: "600",
		marginLeft: 8,
	},
	timeEntryCard: {
		marginHorizontal: 16,
		marginBottom: 16,
		backgroundColor: "#fff",
		borderRadius: 12,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 2,
		elevation: 2,
		overflow: "hidden",
	},
	timeEntryHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		padding: 16,
		borderBottomWidth: 1,
		borderBottomColor: "#f0f0f0",
	},
	headerLeftSection: {
		flexDirection: "row",
		alignItems: "center",
		flex: 1,
	},
	selectionCheckbox: {
		marginRight: 12,
	},
	dateTimeText: {
		fontSize: 16,
		fontWeight: "600",
		color: "#333",
	},
	timeEntryDetails: {
		padding: 16,
	},
	detailRow: {
		flexDirection: "row",
		marginBottom: 8,
	},
	detailLabel: {
		fontSize: 15,
		color: "#666",
		width: 80,
	},
	detailValue: {
		fontSize: 15,
		color: "#333",
		flex: 1,
	},
	connectedEventsSection: {
		marginTop: 16,
	},
	sectionTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "#333",
		marginBottom: 8,
	},
	connectedEventContainer: {
		marginBottom: 16,
		borderWidth: 1,
		borderColor: "#f0f0f0",
		borderRadius: 8,
		overflow: "hidden",
	},
	connectedEventItem: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 10,
		paddingHorizontal: 12,
		backgroundColor: "#f7f9fc",
		borderBottomColor: "#f0f0f0",
	},
	eventFormResponsesSection: {
		padding: 12,
		backgroundColor: "#ffffff",
	},
	eventFormTitle: {
		fontSize: 14,
		fontWeight: "500",
		color: "#666",
		marginBottom: 8,
	},
	notesSection: {
		marginTop: 16,
	},
	notesText: {
		fontSize: 15,
		color: "#333",
		lineHeight: 22,
	},
	formResponsesSection: {
		marginTop: 16,
		borderTopWidth: 1,
		borderTopColor: "#f0f0f0",
		paddingTop: 16,
	},
	formResponseItem: {
		marginBottom: 12,
	},
	formFieldLabel: {
		fontSize: 14,
		color: "#666",
		marginBottom: 4,
	},
	formFieldValue: {
		fontSize: 15,
		color: "#333",
	},
	multiplierValue: {
		fontSize: 14,
		color: "#007AFF",
	},
	editHistorySection: {
		marginTop: 16,
		paddingTop: 12,
		borderTopWidth: 1,
		borderTopColor: "#f0f0f0",
	},
	editHistoryItem: {
		marginBottom: 12,
		padding: 10,
		backgroundColor: "#f0f7ff",
		borderRadius: 6,
	},
	editTimestamp: {
		fontSize: 13,
		color: "#666",
		marginBottom: 4,
	},
	editSummary: {
		fontSize: 14,
		color: "#333",
		fontWeight: "500",
	},
	entryActions: {
		marginTop: 16,
		flexDirection: "row",
		justifyContent: "flex-end",
	},
	editButton: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 8,
		paddingHorizontal: 12,
		borderRadius: 6,
		backgroundColor: "#f0f7ff",
	},
	editButtonText: {
		marginLeft: 6,
		fontSize: 14,
		fontWeight: "500",
		color: "#007AFF",
	},
	modal: {
		margin: 0,
		justifyContent: "flex-end",
	},
	modalContent: {
		backgroundColor: "#fff",
		borderTopLeftRadius: 12,
		borderTopRightRadius: 12,
		padding: 20,
	},
	modalTitle: {
		fontSize: 18,
		fontWeight: "600",
		color: "#333",
		marginBottom: 4,
		textAlign: "center",
	},
	modalForm: {
		marginBottom: 20,
	},
	modalLabel: {
		fontSize: 15,
		fontWeight: "500",
		color: "#333",
		marginBottom: 8,
	},
	modalInput: {
		height: 44,
		borderWidth: 1,
		borderColor: "#ddd",
		borderRadius: 8,
		paddingHorizontal: 12,
		fontSize: 16,
		marginBottom: 16,
	},
	modalTextArea: {
		height: 100,
		borderWidth: 1,
		borderColor: "#ddd",
		borderRadius: 8,
		paddingHorizontal: 12,
		paddingTop: 12,
		paddingBottom: 12,
		fontSize: 16,
		marginBottom: 16,
		textAlignVertical: "top",
	},
	modalButtons: {
		flexDirection: "row",
		justifyContent: "space-between",
	},
	modalButton: {
		paddingVertical: 12,
		borderRadius: 8,
		alignItems: "center",
		justifyContent: "center",
		flex: 1,
	},
	modalCancelButton: {
		backgroundColor: "#f2f2f2",
		marginRight: 8,
	},
	modalSaveButton: {
		backgroundColor: "#007AFF",
		marginLeft: 8,
	},
	modalCancelButtonText: {
		fontSize: 16,
		fontWeight: "600",
		color: "#666",
	},
	modalSaveButtonText: {
		fontSize: 16,
		fontWeight: "600",
		color: "#fff",
	},
	exportOptionRow: {
		marginBottom: 20,
	},
	exportOptions: {
		flexDirection: "row",
		marginTop: 8,
	},
	exportOption: {
		flex: 1,
		paddingVertical: 10,
		alignItems: "center",
		borderWidth: 1,
		borderColor: "#ddd",
		marginHorizontal: 4,
		borderRadius: 6,
	},
	selectedExportOption: {
		borderColor: "#007AFF",
		backgroundColor: "#f0f7ff",
	},
	exportOptionText: {
		fontSize: 15,
		color: "#666",
	},
	selectedExportOptionText: {
		color: "#007AFF",
		fontWeight: "500",
	},
	fileResponseGrid: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 10,
		marginTop: 8,
	},
	fileResponseItem: {
		width: 80,
		height: 80,
		borderRadius: 8,
		overflow: "hidden",
		borderWidth: 1,
		borderColor: "#eee",
	},
	fileResponseImage: {
		width: "100%",
		height: "100%",
		resizeMode: "cover",
	},
	videoOverlay: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: "rgba(0,0,0,0.3)",
		justifyContent: "center",
		alignItems: "center",
	},
	fileResponseDoc: {
		width: "100%",
		height: "100%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "#f5f5f5",
	},
	fileResponseVideo: {
		width: "100%",
		height: "100%",
		position: "relative",
	},
	fileResponseName: {
		fontSize: 10,
		color: "#666",
		textAlign: "center",
		paddingHorizontal: 4,
		marginTop: 4,
	},
	eventTitle: {
		fontSize: 15,
		fontWeight: "500",
		color: "#333",
		marginLeft: 8,
	},
});
