import { StyleSheet } from "react-native";

/** Presentation only — extracted verbatim from EditSheet.tsx. */
export const styles = StyleSheet.create({
	sheetBackground: {
		backgroundColor: "white",
	},
	sheetIndicator: {
		backgroundColor: "#ccc",
		width: 40,
		height: 4,
	},
	sheetHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 20,
		paddingVertical: 16,
		borderBottomWidth: 1,
		borderBottomColor: "#eaeaea",
	},
	sheetContent: {
		padding: 20,
		paddingBottom: 40,
	},
	modalTitle: {
		fontSize: 18,
		fontWeight: "600",
		color: "#333",
		flex: 1,
		textAlign: "center",
	},
	modalForm: {
		marginBottom: 20,
	},
	sectionTitle: {
		fontSize: 17,
		fontWeight: "600",
		color: "#333",
		marginBottom: 12,
	},
	timeSection: {
		marginBottom: 24,
		backgroundColor: "#f9f9f9",
		padding: 16,
		borderRadius: 12,
	},
	notesSection: {
		marginBottom: 24,
	},
	formSection: {
		marginBottom: 24,
		backgroundColor: "#f9f9f9",
		padding: 16,
		borderRadius: 12,
	},
	connectedEventsSection: {
		marginBottom: 24,
	},
	connectedEventCard: {
		marginBottom: 16,
		backgroundColor: "#f9f9f9",
		padding: 16,
		borderRadius: 12,
		borderLeftWidth: 3,
		borderLeftColor: "#007AFF",
	},
	connectedEventHeader: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 12,
		paddingBottom: 8,
		borderBottomWidth: 1,
		borderBottomColor: "#eee",
	},
	connectedEventTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "#333",
		marginLeft: 8,
	},
	summarySection: {
		marginBottom: 16,
	},
	summarySubtitle: {
		fontSize: 14,
		color: "#666",
		marginBottom: 8,
	},
	timeRow: {
		marginBottom: 16,
	},
	durationRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		marginTop: 8,
		paddingTop: 12,
		borderTopWidth: 1,
		borderTopColor: "#eee",
	},
	durationText: {
		fontSize: 16,
		fontWeight: "600",
		color: "#333",
	},
	modalLabel: {
		fontSize: 15,
		fontWeight: "500",
		color: "#333",
		marginBottom: 8,
	},
	timePickerButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		height: 44,
		borderWidth: 1,
		borderColor: "#ddd",
		borderRadius: 8,
		paddingHorizontal: 12,
		backgroundColor: "#fff",
	},
	timePickerText: {
		fontSize: 16,
		color: "#333",
	},
	datePickerButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		height: 44,
		borderWidth: 1,
		borderColor: "#ddd",
		borderRadius: 8,
		paddingHorizontal: 12,
		backgroundColor: "#fff",
	},
	datePickerText: {
		fontSize: 16,
		color: "#333",
	},
	modalInput: {
		height: 44,
		borderWidth: 1,
		borderColor: "#ddd",
		borderRadius: 8,
		paddingHorizontal: 12,
		fontSize: 16,
		marginBottom: 16,
		backgroundColor: "#fff",
	},
	modalTextArea: {
		minHeight: 100,
		borderWidth: 1,
		borderColor: "#ddd",
		borderRadius: 8,
		paddingHorizontal: 12,
		paddingTop: 12,
		paddingBottom: 12,
		fontSize: 16,
		textAlignVertical: "top",
		backgroundColor: "#fff",
	},
	formField: {
		marginBottom: 16,
	},
	fieldLabel: {
		fontSize: 15,
		fontWeight: "500",
		color: "#333",
		marginBottom: 8,
	},
	formInput: {
		height: 44,
		borderWidth: 1,
		borderColor: "#ddd",
		borderRadius: 8,
		paddingHorizontal: 12,
		fontSize: 16,
		backgroundColor: "#fff",
	},
	dropdownContainer: {
		zIndex: 1000,
		marginBottom: 16,
	},
	dropdown: {
		borderColor: "#ddd",
		backgroundColor: "#fff",
	},
	dropdownList: {
		borderColor: "#ddd",
	},
	requiredMark: {
		color: "#FF3B30",
		fontWeight: "bold",
	},
	modalButtons: {
		flexDirection: "row",
		justifyContent: "space-between",
	},
	modalButton: {
		paddingVertical: 12,
		borderRadius: 8,
		alignItems: "center",
		justifyContent: "center",
		flex: 1,
	},
	modalCancelButton: {
		backgroundColor: "#f2f2f2",
		marginRight: 8,
	},
	modalSaveButton: {
		backgroundColor: "#007AFF",
		marginLeft: 8,
	},
	modalCancelButtonText: {
		fontSize: 16,
		fontWeight: "600",
		color: "#666",
	},
	modalSaveButtonText: {
		fontSize: 16,
		fontWeight: "600",
		color: "#fff",
	},
	deleteButtonContainer: {
		marginTop: 16,
		alignItems: "center",
	},
	deleteButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#FF3B30",
		paddingVertical: 12,
		paddingHorizontal: 20,
		borderRadius: 8,
	},
	deleteButtonText: {
		fontSize: 16,
		fontWeight: "600",
		color: "#fff",
		marginLeft: 8,
	},
	fieldAttachmentContainer: {
		marginTop: 8,
		marginBottom: 16,
		borderWidth: 1,
		borderColor: "#eee",
		borderRadius: 8,
		padding: 12,
		backgroundColor: "#fff",
	},
	eventTitleContainer: {
		flex: 1,
		marginLeft: 8,
	},
	eventTitleInput: {
		fontSize: 16,
		fontWeight: "600",
		color: "#333",
		padding: 0,
	},
	deleteEventButton: {
		padding: 4,
	},
	addEventButton: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#f0f8ff",
		padding: 12,
		borderRadius: 8,
		justifyContent: "center",
		marginTop: 8,
	},
	addEventButtonText: {
		color: "#007AFF",
		fontWeight: "600",
		fontSize: 15,
		marginLeft: 8,
	},
	pauseDurationRow: {
		marginTop: 12,
		borderTopWidth: 1,
		borderTopColor: "#eee",
		paddingTop: 12,
	},
	pauseDurationInputContainer: {
		flexDirection: "row",
		alignItems: "center",
		marginTop: 8,
	},
	pauseDurationInputWrapper: {
		flexDirection: "row",
		alignItems: "center",
		marginRight: 16,
	},
	pauseDurationInput: {
		width: 50,
		height: 44,
		borderWidth: 1,
		borderColor: "#ddd",
		borderRadius: 8,
		paddingHorizontal: 12,
		fontSize: 16,
		backgroundColor: "#fff",
		textAlign: "center",
	},
	pauseDurationUnit: {
		fontSize: 16,
		fontWeight: "600",
		color: "#333",
		marginLeft: 8,
	},
});
