import { StyleSheet } from "react-native";
import { Theme } from "../../theme";

/** Presentation only — extracted verbatim from EditSheet.tsx. */
export const editSheetStyles = (theme: Theme) =>
	StyleSheet.create({
		sheetBackground: {
			backgroundColor: theme.colors.surface,
		},
		sheetIndicator: {
			backgroundColor: theme.colors.border,
			width: 40,
			height: 4,
		},
		sheetHeader: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			paddingHorizontal: 20,
			paddingVertical: 16,
			borderBottomWidth: 1,
			borderBottomColor: theme.colors.border,
		},
		sheetContent: {
			padding: 20,
			paddingBottom: 40,
		},
		modalTitle: {
			fontSize: 18,
			fontWeight: "600",
			color: theme.colors.text,
			flex: 1,
			textAlign: "center",
		},
		modalForm: {
			marginBottom: 20,
		},
		sectionTitle: {
			fontSize: 17,
			fontWeight: "600",
			color: theme.colors.text,
			marginBottom: 12,
		},
		timeSection: {
			marginBottom: 24,
			backgroundColor: theme.colors.surfaceSunken,
			padding: 16,
			borderRadius: 12,
		},
		notesSection: {
			marginBottom: 24,
		},
		formSection: {
			marginBottom: 24,
			backgroundColor: theme.colors.surfaceSunken,
			padding: 16,
			borderRadius: 12,
		},
		connectedEventsSection: {
			marginBottom: 24,
		},
		connectedEventCard: {
			marginBottom: 16,
			backgroundColor: theme.colors.surfaceSunken,
			padding: 16,
			borderRadius: 12,
			borderLeftWidth: 3,
			borderLeftColor: theme.colors.accent,
		},
		connectedEventHeader: {
			flexDirection: "row",
			alignItems: "center",
			marginBottom: 12,
			paddingBottom: 8,
			borderBottomWidth: 1,
			borderBottomColor: theme.colors.border,
		},
		connectedEventTitle: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.text,
			marginLeft: 8,
		},
		summarySection: {
			marginBottom: 16,
		},
		summarySubtitle: {
			fontSize: 14,
			color: theme.colors.textSecondary,
			marginBottom: 8,
		},
		timeRow: {
			marginBottom: 16,
		},
		durationRow: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			marginTop: 8,
			paddingTop: 12,
			borderTopWidth: 1,
			borderTopColor: theme.colors.border,
		},
		durationText: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.text,
		},
		modalLabel: {
			fontSize: 15,
			fontWeight: "500",
			color: theme.colors.text,
			marginBottom: 8,
		},
		timePickerButton: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			height: 44,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			paddingHorizontal: 12,
			backgroundColor: theme.colors.surface,
		},
		timePickerText: {
			fontSize: 16,
			color: theme.colors.text,
		},
		datePickerButton: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			height: 44,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			paddingHorizontal: 12,
			backgroundColor: theme.colors.surface,
		},
		datePickerText: {
			fontSize: 16,
			color: theme.colors.text,
		},
		modalInput: {
			height: 44,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			paddingHorizontal: 12,
			fontSize: 16,
			marginBottom: 16,
			backgroundColor: theme.colors.surface,
		},
		modalTextArea: {
			minHeight: 100,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			paddingHorizontal: 12,
			paddingTop: 12,
			paddingBottom: 12,
			fontSize: 16,
			textAlignVertical: "top",
			backgroundColor: theme.colors.surface,
		},
		formField: {
			marginBottom: 16,
		},
		fieldLabel: {
			fontSize: 15,
			fontWeight: "500",
			color: theme.colors.text,
			marginBottom: 8,
		},
		formInput: {
			height: 44,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			paddingHorizontal: 12,
			fontSize: 16,
			backgroundColor: theme.colors.surface,
		},
		dropdownContainer: {
			zIndex: 1000,
			marginBottom: 16,
		},
		dropdown: {
			borderColor: theme.colors.border,
			backgroundColor: theme.colors.surface,
		},
		dropdownList: {
			borderColor: theme.colors.border,
		},
		requiredMark: {
			color: theme.colors.danger,
			fontWeight: "bold",
		},
		modalButtons: {
			flexDirection: "row",
			justifyContent: "space-between",
		},
		modalButton: {
			paddingVertical: 12,
			borderRadius: 8,
			alignItems: "center",
			justifyContent: "center",
			flex: 1,
		},
		modalCancelButton: {
			backgroundColor: theme.colors.surfaceSunken,
			marginRight: 8,
		},
		modalSaveButton: {
			backgroundColor: theme.colors.accent,
			marginLeft: 8,
		},
		modalCancelButtonText: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.textSecondary,
		},
		modalSaveButtonText: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.surface,
		},
		deleteButtonContainer: {
			marginTop: 16,
			alignItems: "center",
		},
		deleteButton: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			backgroundColor: theme.colors.danger,
			paddingVertical: 12,
			paddingHorizontal: 20,
			borderRadius: 8,
		},
		deleteButtonText: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.surface,
			marginLeft: 8,
		},
		fieldAttachmentContainer: {
			marginTop: 8,
			marginBottom: 16,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			padding: 12,
			backgroundColor: theme.colors.surface,
		},
		eventTitleContainer: {
			flex: 1,
			marginLeft: 8,
		},
		eventTitleInput: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.text,
			padding: 0,
		},
		deleteEventButton: {
			padding: 4,
		},
		addEventButton: {
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: theme.colors.accentSubtle,
			padding: 12,
			borderRadius: 8,
			justifyContent: "center",
			marginTop: 8,
		},
		addEventButtonText: {
			color: theme.colors.accent,
			fontWeight: "600",
			fontSize: 15,
			marginLeft: 8,
		},
		pauseDurationRow: {
			marginTop: 12,
			borderTopWidth: 1,
			borderTopColor: theme.colors.border,
			paddingTop: 12,
		},
		pauseDurationInputContainer: {
			flexDirection: "row",
			alignItems: "center",
			marginTop: 8,
		},
		pauseDurationInputWrapper: {
			flexDirection: "row",
			alignItems: "center",
			marginRight: 16,
		},
		pauseDurationInput: {
			width: 50,
			height: 44,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			paddingHorizontal: 12,
			fontSize: 16,
			backgroundColor: theme.colors.surface,
			textAlign: "center",
		},
		pauseDurationUnit: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.text,
			marginLeft: 8,
		},
	});
