import { StyleSheet } from "react-native";
import { Theme } from "../../theme";

/** Presentation only — extracted verbatim from ProfilePage.tsx. */
export const profileStyles = (theme: Theme) =>
	StyleSheet.create({
		container: {
			flex: 1,
			backgroundColor: theme.colors.surfaceSunken,
		},
		header: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			paddingHorizontal: 16,
			paddingVertical: 12,
			backgroundColor: theme.colors.surface,
			borderBottomWidth: 1,
			borderBottomColor: theme.colors.border,
		},
		headerTitle: {
			fontSize: 18,
			fontWeight: "600",
			color: theme.colors.text,
			textAlign: "center",
			flex: 1,
		},
		backButton: {
			padding: 8,
		},
		scrollView: {
			flex: 1,
		},
		contentContainer: {
			padding: 16,
			paddingBottom: 32,
		},
		profileCard: {
			backgroundColor: theme.colors.surface,
			borderRadius: 12,
			marginBottom: 16,
			overflow: "hidden",
			shadowColor: theme.colors.shadow,
			shadowOffset: { width: 0, height: 1 },
			shadowOpacity: 0.1,
			shadowRadius: 3,
			elevation: 2,
		},
		profileHeader: {
			flexDirection: "row",
			alignItems: "center",
			padding: 16,
		},
		avatarContainer: {
			width: 60,
			height: 60,
			borderRadius: 30,
			backgroundColor: theme.colors.accentSubtle,
			alignItems: "center",
			justifyContent: "center",
			marginRight: 16,
		},
		avatarText: {
			fontSize: 22,
			fontWeight: "600",
			color: theme.colors.accent,
		},
		nameContainer: {
			flex: 1,
		},
		nameText: {
			fontSize: 18,
			fontWeight: "600",
			color: theme.colors.text,
			marginBottom: 4,
		},
		editText: {
			fontSize: 12,
			color: theme.colors.textTertiary,
			fontStyle: "italic",
		},
		card: {
			backgroundColor: theme.colors.surface,
			borderRadius: 12,
			marginBottom: 16,
			overflow: "hidden",
			shadowColor: theme.colors.shadow,
			shadowOffset: { width: 0, height: 1 },
			shadowOpacity: 0.1,
			shadowRadius: 3,
			elevation: 2,
		},
		dangerCard: {
			backgroundColor: theme.colors.surface,
			borderRadius: 12,
			marginBottom: 16,
			overflow: "hidden",
			shadowColor: theme.colors.shadow,
			shadowOffset: { width: 0, height: 1 },
			shadowOpacity: 0.1,
			shadowRadius: 3,
			elevation: 2,
			borderLeftWidth: 4,
			borderLeftColor: theme.colors.danger,
		},
		cardHeader: {
			flexDirection: "row",
			alignItems: "center",
			paddingHorizontal: 16,
			paddingTop: 16,
			paddingBottom: 12,
			borderBottomWidth: 1,
			borderBottomColor: theme.colors.border,
		},
		cardIcon: {
			marginRight: 10,
		},
		cardTitle: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.text,
		},
		cardContent: {
			padding: 16,
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
		},
		valueText: {
			fontSize: 15,
			color: theme.colors.textSecondary,
			flex: 1,
		},
		actionButton: {
			paddingHorizontal: 16,
			paddingVertical: 8,
			borderRadius: 8,
			borderWidth: 1,
			borderColor: theme.colors.accent,
			backgroundColor: "transparent",
		},
		actionButtonText: {
			fontSize: 13,
			fontWeight: "500",
			color: theme.colors.accent,
		},
		dropdown: {
			height: 50,
			width: "100%",
			borderColor: theme.colors.border,
			borderWidth: 1,
			borderRadius: 8,
			paddingHorizontal: 16,
			marginBottom: 16,
			backgroundColor: theme.colors.surfaceSunken, // Add background color for better contrast
		},
		dropdownPlaceholder: {
			color: theme.colors.textTertiary,
			fontSize: 16,
		},
		dropdownSelectedText: {
			color: theme.colors.text,
			fontSize: 16,
			fontWeight: "500", // Make selected text more visible
		},
		joinButton: {
			paddingVertical: 12,
			borderRadius: 8,
			borderWidth: 1,
			borderColor: theme.colors.accent,
			backgroundColor: theme.colors.accentSubtle,
		},
		joinButtonText: {
			fontSize: 14,
			fontWeight: "500",
			color: theme.colors.accent,
		},
		resetButton: {
			paddingVertical: 12,
			borderRadius: 8,
			borderWidth: 1,
			borderColor: theme.colors.textSecondary,
			backgroundColor: theme.colors.surfaceSunken,
			flexDirection: "row",
			justifyContent: "center",
			alignItems: "center",
		},
		resetButtonText: {
			fontSize: 14,
			fontWeight: "500",
			color: theme.colors.textSecondary,
		},
		deleteButton: {
			paddingVertical: 12,
			borderRadius: 8,
			borderWidth: 1,
			borderColor: theme.colors.danger,
			backgroundColor: theme.colors.dangerSubtle,
			flexDirection: "row",
			justifyContent: "center",
			alignItems: "center",
		},
		deleteButtonText: {
			fontSize: 14,
			fontWeight: "500",
			color: theme.colors.danger,
		},
	});
