import { StyleSheet } from "react-native";

/** Presentation only — extracted verbatim from ProfilePage.tsx. */
export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#f8f9fa",
	},
	header: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 16,
		paddingVertical: 12,
		backgroundColor: "white",
		borderBottomWidth: 1,
		borderBottomColor: "#e1e4e8",
	},
	headerTitle: {
		fontSize: 18,
		fontWeight: "600",
		color: "#333",
		textAlign: "center",
		flex: 1,
	},
	backButton: {
		padding: 8,
	},
	scrollView: {
		flex: 1,
	},
	contentContainer: {
		padding: 16,
		paddingBottom: 32,
	},
	profileCard: {
		backgroundColor: "white",
		borderRadius: 12,
		marginBottom: 16,
		overflow: "hidden",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 3,
		elevation: 2,
	},
	profileHeader: {
		flexDirection: "row",
		alignItems: "center",
		padding: 16,
	},
	avatarContainer: {
		width: 60,
		height: 60,
		borderRadius: 30,
		backgroundColor: "#e6f2ff",
		alignItems: "center",
		justifyContent: "center",
		marginRight: 16,
	},
	avatarText: {
		fontSize: 22,
		fontWeight: "600",
		color: "#2089dc",
	},
	nameContainer: {
		flex: 1,
	},
	nameText: {
		fontSize: 18,
		fontWeight: "600",
		color: "#333",
		marginBottom: 4,
	},
	editText: {
		fontSize: 12,
		color: "#888",
		fontStyle: "italic",
	},
	card: {
		backgroundColor: "white",
		borderRadius: 12,
		marginBottom: 16,
		overflow: "hidden",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 3,
		elevation: 2,
	},
	dangerCard: {
		backgroundColor: "white",
		borderRadius: 12,
		marginBottom: 16,
		overflow: "hidden",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 3,
		elevation: 2,
		borderLeftWidth: 4,
		borderLeftColor: "#d32f2f",
	},
	cardHeader: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 16,
		paddingTop: 16,
		paddingBottom: 12,
		borderBottomWidth: 1,
		borderBottomColor: "#f0f0f0",
	},
	cardIcon: {
		marginRight: 10,
	},
	cardTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "#333",
	},
	cardContent: {
		padding: 16,
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	valueText: {
		fontSize: 15,
		color: "#444",
		flex: 1,
	},
	actionButton: {
		paddingHorizontal: 16,
		paddingVertical: 8,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#2089dc",
		backgroundColor: "transparent",
	},
	actionButtonText: {
		fontSize: 13,
		fontWeight: "500",
		color: "#2089dc",
	},
	dropdown: {
		height: 50,
		width: "100%",
		borderColor: "#e0e0e0",
		borderWidth: 1,
		borderRadius: 8,
		paddingHorizontal: 16,
		marginBottom: 16,
		backgroundColor: "#f9f9f9", // Add background color for better contrast
	},
	dropdownPlaceholder: {
		color: "#999",
		fontSize: 16,
	},
	dropdownSelectedText: {
		color: "#333",
		fontSize: 16,
		fontWeight: "500", // Make selected text more visible
	},
	joinButton: {
		paddingVertical: 12,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#2089dc",
		backgroundColor: "#e6f2ff",
	},
	joinButtonText: {
		fontSize: 14,
		fontWeight: "500",
		color: "#2089dc",
	},
	resetButton: {
		paddingVertical: 12,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#666",
		backgroundColor: "#f5f5f5",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	resetButtonText: {
		fontSize: 14,
		fontWeight: "500",
		color: "#666",
	},
	deleteButton: {
		paddingVertical: 12,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#d32f2f",
		backgroundColor: "#ffebee",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	deleteButtonText: {
		fontSize: 14,
		fontWeight: "500",
		color: "#d32f2f",
	},
});
