import { StyleSheet, Platform } from "react-native";

/** Presentation only — extracted verbatim from CompanyCustomForm.tsx. */
export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "white",
	},
	centered: {
		justifyContent: "center",
		alignItems: "center",
	},
	header: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		padding: 16,
		backgroundColor: "white",
		borderBottomWidth: 1,
		borderBottomColor: "#e1e4e8",
	},
	headerTitle: {
		fontSize: 18,
		fontWeight: "600",
		color: "#333",
	},
	saveButton: {
		fontSize: 16,
		fontWeight: "600",
		color: "#007AFF",
	},
	content: {
		flex: 1,
		padding: 16,
	},
	formControl: {
		marginBottom: 20,
	},
	label: {
		fontSize: 16,
		fontWeight: "500",
		marginBottom: 8,
		color: "#333",
	},
	input: {
		height: 48,
		borderWidth: 1,
		borderColor: "#ccc",
		borderRadius: 8,
		paddingHorizontal: 12,
		fontSize: 16,
		backgroundColor: "white",
	},
	textArea: {
		minHeight: 80,
		borderWidth: 1,
		borderColor: "#ccc",
		borderRadius: 8,
		paddingHorizontal: 12,
		paddingTop: 12,
		fontSize: 16,
		backgroundColor: "white",
		textAlignVertical: "top",
	},
	switchRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		marginBottom: 8,
	},
	helperText: {
		fontSize: 14,
		color: "#666",
		marginTop: 4,
	},
	formSection: {
		marginTop: 10,
		marginBottom: 24,
	},
	sectionTitle: {
		fontSize: 18,
		fontWeight: "600",
		marginBottom: 16,
		color: "#333",
	},
	emptyState: {
		alignItems: "center",
		justifyContent: "center",
		padding: 30,
		backgroundColor: "white",
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#e1e4e8",
		borderStyle: "dashed",
	},
	emptyStateText: {
		marginTop: 10,
		fontSize: 15,
		color: "#666",
		textAlign: "center",
	},
	fieldItem: {
		backgroundColor: "white",
		padding: 16,
		borderRadius: 8,
		marginBottom: 10,
		borderWidth: 1,
		borderColor: "#e1e4e8",
	},
	selectedField: {
		borderColor: "#007AFF",
		backgroundColor: "#f0f7ff",
	},
	draggingField: {
		opacity: 0.7,
		transform: [{ scale: 1.05 }],
		elevation: 5,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.2,
		shadowRadius: 4,
	},
	fieldContent: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
	},
	fieldInfo: {
		flexDirection: "row",
		alignItems: "flex-start",
		flex: 1,
		flexWrap: "wrap",
		paddingRight: 10,
	},
	fieldType: {
		fontSize: 12,
		backgroundColor: "#e1e4e8",
		paddingHorizontal: 8,
		paddingVertical: 3,
		borderRadius: 4,
		color: "#555",
		marginRight: 8,
		marginTop: 2,
	},
	fieldLabel: {
		fontSize: 16,
		color: "#333",
		flex: 1,
		flexShrink: 1,
	},
	expandableInput: {
		minHeight: 48,
		borderWidth: 1,
		borderColor: "#ccc",
		borderRadius: 8,
		paddingHorizontal: 12,
		paddingVertical: 8,
		fontSize: 16,
		backgroundColor: "white",
		textAlignVertical: "center",
	},
	fieldActions: {
		flexDirection: "row",
		alignItems: "center",
		width: 70,
		justifyContent: "space-between",
		marginLeft: 8,
		flexShrink: 0,
	},
	requiredBadge: {
		backgroundColor: "#ff9500",
		marginLeft: 8,
		paddingHorizontal: 6,
		paddingVertical: 2,
		borderRadius: 4,
		marginTop: 2,
		flexShrink: 0,
	},
	requiredText: {
		fontSize: 10,
		color: "white",
		fontWeight: "600",
	},
	addButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 12,
		backgroundColor: "white",
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#007AFF",
		marginTop: 10,
	},
	addButtonText: {
		marginLeft: 8,
		color: "#007AFF",
		fontWeight: "500",
		fontSize: 16,
	},
	charCount: {
		fontSize: 12,
		color: "#666",
		textAlign: "right",
		marginTop: 4,
	},
	fieldEditor: {
		backgroundColor: "white",
		padding: 16,
		borderRadius: 8,
		marginVertical: 16,
		borderWidth: 1,
		borderColor: "#e1e4e8",
		// These are important for proper dropdown rendering
		zIndex: 1000,
		elevation: Platform.OS === "android" ? 3 : 0,
		position: "relative",
	},
	editorHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 16,
		paddingBottom: 12,
		borderBottomWidth: 1,
		borderBottomColor: "#e1e4e8",
	},
	editorTitle: {
		fontSize: 18,
		fontWeight: "600",
		color: "#333",
	},
	dropdown: {
		borderColor: "#ccc",
		height: 48,
		backgroundColor: "white",
	},
	dropdownList: {
		borderColor: "#ccc",
		backgroundColor: "white",
		elevation: 5,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
	},
	saveFieldButton: {
		backgroundColor: "#007AFF",
		borderRadius: 8,
		paddingVertical: 12,
		alignItems: "center",
		marginTop: 16,
	},
	saveFieldText: {
		color: "white",
		fontSize: 16,
		fontWeight: "600",
	},
	previewButton: {
		backgroundColor: "#5856d6",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 12,
		borderRadius: 8,
		marginVertical: 16,
	},
	previewButtonText: {
		color: "white",
		marginLeft: 8,
		fontSize: 16,
		fontWeight: "500",
	},
	preview: {
		backgroundColor: "#f0f0f0",
		borderRadius: 8,
		padding: 16,
		marginBottom: 24,
	},
	previewTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "#333",
		marginBottom: 12,
	},
	previewForm: {
		backgroundColor: "white",
		borderRadius: 8,
		padding: 16,
		borderWidth: 1,
		borderColor: "#ddd",
	},
	previewFormTitle: {
		fontSize: 18,
		fontWeight: "600",
		color: "#333",
		marginBottom: 8,
	},
	previewDescription: {
		fontSize: 14,
		color: "#666",
		marginBottom: 16,
	},
	previewField: {
		marginBottom: 16,
	},
	previewLabel: {
		fontSize: 15,
		fontWeight: "500",
		marginBottom: 6,
		color: "#333",
	},
	required: {
		color: "red",
	},
	previewInput: {
		height: 42,
		borderWidth: 1,
		borderColor: "#ccc",
		borderRadius: 6,
		paddingHorizontal: 10,
	},
	previewTotal: {
		fontSize: 14,
		color: "#666",
		marginTop: 4,
	},
	checkboxPreview: {
		flexDirection: "row",
		alignItems: "center",
	},
	checkboxPreviewLabel: {
		marginLeft: 8,
		fontSize: 15,
		color: "#333",
	},
	previewSelect: {
		height: 42,
		borderWidth: 1,
		borderColor: "#ccc",
		borderRadius: 6,
		paddingHorizontal: 12,
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	previewSelectText: {
		fontSize: 15,
		color: "#999",
	},
	previewDate: {
		height: 42,
		borderWidth: 1,
		borderColor: "#ccc",
		borderRadius: 6,
		paddingHorizontal: 12,
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	previewDateText: {
		fontSize: 15,
		color: "#999",
	},
	labelWithHelp: {
		flexDirection: "row",
		alignItems: "center",
	},
	multiplierContainer: {
		marginTop: 16,
	},
	previewMultiplier: {
		marginTop: 4,
	},
	previewMultiplierText: {
		fontSize: 14,
		color: "#666",
	},
	previewFileUpload: {
		height: 100,
		borderWidth: 1,
		borderColor: "#ccc",
		borderStyle: "dashed",
		borderRadius: 8,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "#f9f9f9",
	},
	previewUploadText: {
		marginTop: 8,
		color: "#666",
		fontSize: 14,
	},
	checklistPreview: {
		gap: 10,
	},
	quickEditBadge: {
		backgroundColor: "#34c759",
		marginLeft: 8,
		paddingHorizontal: 6,
		paddingVertical: 2,
		borderRadius: 4,
		marginTop: 2,
		flexShrink: 0,
	},
	quickEditText: {
		fontSize: 10,
		color: "white",
		fontWeight: "600",
	},
});
