import { StyleSheet, Platform } from "react-native";
import { Theme } from "../../../theme";

/** Presentation only — extracted verbatim from CompanyCustomForm.tsx. */
export const customFormStyles = (theme: Theme) =>
	StyleSheet.create({
		container: {
			flex: 1,
			backgroundColor: theme.colors.surface,
		},
		centered: {
			justifyContent: "center",
			alignItems: "center",
		},
		header: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			padding: 16,
			backgroundColor: theme.colors.surface,
			borderBottomWidth: 1,
			borderBottomColor: theme.colors.border,
		},
		headerTitle: {
			fontSize: 18,
			fontWeight: "600",
			color: theme.colors.text,
		},
		saveButton: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.accent,
		},
		content: {
			flex: 1,
			padding: 16,
		},
		formControl: {
			marginBottom: 20,
		},
		label: {
			fontSize: 16,
			fontWeight: "500",
			marginBottom: 8,
			color: theme.colors.text,
		},
		input: {
			height: 48,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			paddingHorizontal: 12,
			fontSize: 16,
			backgroundColor: theme.colors.surface,
		},
		textArea: {
			minHeight: 80,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			paddingHorizontal: 12,
			paddingTop: 12,
			fontSize: 16,
			backgroundColor: theme.colors.surface,
			textAlignVertical: "top",
		},
		switchRow: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			marginBottom: 8,
		},
		helperText: {
			fontSize: 14,
			color: theme.colors.textSecondary,
			marginTop: 4,
		},
		formSection: {
			marginTop: 10,
			marginBottom: 24,
		},
		sectionTitle: {
			fontSize: 18,
			fontWeight: "600",
			marginBottom: 16,
			color: theme.colors.text,
		},
		emptyState: {
			alignItems: "center",
			justifyContent: "center",
			padding: 30,
			backgroundColor: theme.colors.surface,
			borderRadius: 8,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderStyle: "dashed",
		},
		emptyStateText: {
			marginTop: 10,
			fontSize: 15,
			color: theme.colors.textSecondary,
			textAlign: "center",
		},
		fieldItem: {
			backgroundColor: theme.colors.surface,
			padding: 16,
			borderRadius: 8,
			marginBottom: 10,
			borderWidth: 1,
			borderColor: theme.colors.border,
		},
		selectedField: {
			borderColor: theme.colors.accent,
			backgroundColor: theme.colors.accentSubtle,
		},
		draggingField: {
			opacity: 0.7,
			transform: [{ scale: 1.05 }],
			elevation: 5,
			shadowColor: theme.colors.shadow,
			shadowOffset: { width: 0, height: 4 },
			shadowOpacity: 0.2,
			shadowRadius: 4,
		},
		fieldContent: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "flex-start",
		},
		fieldInfo: {
			flexDirection: "row",
			alignItems: "flex-start",
			flex: 1,
			flexWrap: "wrap",
			paddingRight: 10,
		},
		fieldType: {
			fontSize: 12,
			backgroundColor: theme.colors.border,
			paddingHorizontal: 8,
			paddingVertical: 3,
			borderRadius: 4,
			color: theme.colors.textSecondary,
			marginRight: 8,
			marginTop: 2,
		},
		fieldLabel: {
			fontSize: 16,
			color: theme.colors.text,
			flex: 1,
			flexShrink: 1,
		},
		expandableInput: {
			minHeight: 48,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			paddingHorizontal: 12,
			paddingVertical: 8,
			fontSize: 16,
			backgroundColor: theme.colors.surface,
			textAlignVertical: "center",
		},
		fieldActions: {
			flexDirection: "row",
			alignItems: "center",
			width: 70,
			justifyContent: "space-between",
			marginLeft: 8,
			flexShrink: 0,
		},
		requiredBadge: {
			backgroundColor: theme.colors.warning,
			marginLeft: 8,
			paddingHorizontal: 6,
			paddingVertical: 2,
			borderRadius: 4,
			marginTop: 2,
			flexShrink: 0,
		},
		requiredText: {
			fontSize: 10,
			color: theme.colors.surface,
			fontWeight: "600",
		},
		addButton: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			padding: 12,
			backgroundColor: theme.colors.surface,
			borderRadius: 8,
			borderWidth: 1,
			borderColor: theme.colors.accent,
			marginTop: 10,
		},
		addButtonText: {
			marginLeft: 8,
			color: theme.colors.accent,
			fontWeight: "500",
			fontSize: 16,
		},
		charCount: {
			fontSize: 12,
			color: theme.colors.textSecondary,
			textAlign: "right",
			marginTop: 4,
		},
		fieldEditor: {
			backgroundColor: theme.colors.surface,
			padding: 16,
			borderRadius: 8,
			marginVertical: 16,
			borderWidth: 1,
			borderColor: theme.colors.border,
			// These are important for proper dropdown rendering
			zIndex: 1000,
			elevation: Platform.OS === "android" ? 3 : 0,
			position: "relative",
		},
		editorHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			marginBottom: 16,
			paddingBottom: 12,
			borderBottomWidth: 1,
			borderBottomColor: theme.colors.border,
		},
		editorTitle: {
			fontSize: 18,
			fontWeight: "600",
			color: theme.colors.text,
		},
		dropdown: {
			borderColor: theme.colors.border,
			height: 48,
			backgroundColor: theme.colors.surface,
		},
		dropdownList: {
			borderColor: theme.colors.border,
			backgroundColor: theme.colors.surface,
			elevation: 5,
			shadowColor: theme.colors.shadow,
			shadowOffset: { width: 0, height: 2 },
			shadowOpacity: 0.1,
			shadowRadius: 4,
		},
		saveFieldButton: {
			backgroundColor: theme.colors.accent,
			borderRadius: 8,
			paddingVertical: 12,
			alignItems: "center",
			marginTop: 16,
		},
		saveFieldText: {
			color: theme.colors.surface,
			fontSize: 16,
			fontWeight: "600",
		},
		previewButton: {
			backgroundColor: theme.colors.accent,
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			padding: 12,
			borderRadius: 8,
			marginVertical: 16,
		},
		previewButtonText: {
			color: theme.colors.surface,
			marginLeft: 8,
			fontSize: 16,
			fontWeight: "500",
		},
		preview: {
			backgroundColor: theme.colors.border,
			borderRadius: 8,
			padding: 16,
			marginBottom: 24,
		},
		previewTitle: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.text,
			marginBottom: 12,
		},
		previewForm: {
			backgroundColor: theme.colors.surface,
			borderRadius: 8,
			padding: 16,
			borderWidth: 1,
			borderColor: theme.colors.border,
		},
		previewFormTitle: {
			fontSize: 18,
			fontWeight: "600",
			color: theme.colors.text,
			marginBottom: 8,
		},
		previewDescription: {
			fontSize: 14,
			color: theme.colors.textSecondary,
			marginBottom: 16,
		},
		previewField: {
			marginBottom: 16,
		},
		previewLabel: {
			fontSize: 15,
			fontWeight: "500",
			marginBottom: 6,
			color: theme.colors.text,
		},
		required: {
			color: theme.colors.danger,
		},
		previewInput: {
			height: 42,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 6,
			paddingHorizontal: 10,
		},
		previewTotal: {
			fontSize: 14,
			color: theme.colors.textSecondary,
			marginTop: 4,
		},
		checkboxPreview: {
			flexDirection: "row",
			alignItems: "center",
		},
		checkboxPreviewLabel: {
			marginLeft: 8,
			fontSize: 15,
			color: theme.colors.text,
		},
		previewSelect: {
			height: 42,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 6,
			paddingHorizontal: 12,
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
		},
		previewSelectText: {
			fontSize: 15,
			color: theme.colors.textTertiary,
		},
		previewDate: {
			height: 42,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 6,
			paddingHorizontal: 12,
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
		},
		previewDateText: {
			fontSize: 15,
			color: theme.colors.textTertiary,
		},
		labelWithHelp: {
			flexDirection: "row",
			alignItems: "center",
		},
		multiplierContainer: {
			marginTop: 16,
		},
		previewMultiplier: {
			marginTop: 4,
		},
		previewMultiplierText: {
			fontSize: 14,
			color: theme.colors.textSecondary,
		},
		previewFileUpload: {
			height: 100,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderStyle: "dashed",
			borderRadius: 8,
			justifyContent: "center",
			alignItems: "center",
			backgroundColor: theme.colors.surfaceSunken,
		},
		previewUploadText: {
			marginTop: 8,
			color: theme.colors.textSecondary,
			fontSize: 14,
		},
		checklistPreview: {
			gap: 10,
		},
		quickEditBadge: {
			backgroundColor: theme.colors.success,
			marginLeft: 8,
			paddingHorizontal: 6,
			paddingVertical: 2,
			borderRadius: 4,
			marginTop: 2,
			flexShrink: 0,
		},
		quickEditText: {
			fontSize: 10,
			color: theme.colors.surface,
			fontWeight: "600",
		},
	});
