import { StyleSheet } from "react-native";
import { Theme } from "../../../theme";

/** Presentation only — extracted verbatim from EmployeeList.tsx. */
export const employeeListStyles = (theme: Theme) =>
	StyleSheet.create({
		container: {
			flex: 1,
			backgroundColor: theme.colors.surfaceSunken,
		},
		header: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			paddingHorizontal: 16,
			paddingVertical: 12,
			backgroundColor: theme.colors.surface,
			borderBottomWidth: 1,
			borderBottomColor: theme.colors.border,
		},
		headerTitle: {
			fontSize: 18,
			fontWeight: "600",
			color: theme.colors.text,
			textAlign: "center",
			flex: 1,
		},
		backButton: {
			padding: 8,
		},
		subHeader: {
			backgroundColor: theme.colors.surface,
			paddingVertical: 12,
			paddingHorizontal: 16,
			borderBottomWidth: 1,
			borderBottomColor: theme.colors.border,
		},
		statsContainer: {
			flexDirection: "row",
			justifyContent: "center",
			alignItems: "center",
		},
		statItem: {
			alignItems: "center",
			paddingHorizontal: 24,
		},
		statValue: {
			fontSize: 22,
			fontWeight: "700",
			color: theme.colors.accent,
		},
		statLabel: {
			fontSize: 14,
			color: theme.colors.textSecondary,
			marginTop: 4,
		},
		statDivider: {
			height: 30,
			width: 1,
			backgroundColor: theme.colors.border,
		},
		listContent: {
			padding: 16,
			paddingBottom: 24,
		},
		employeeCard: {
			backgroundColor: theme.colors.surface,
			borderRadius: 12,
			marginBottom: 12,
			overflow: "hidden",
			shadowColor: theme.colors.shadow,
			shadowOffset: { width: 0, height: 1 },
			shadowOpacity: 0.1,
			shadowRadius: 2,
			elevation: 2,
		},
		employeeCardExpanded: {
			shadowOffset: { width: 0, height: 2 },
			shadowOpacity: 0.15,
			shadowRadius: 4,
			elevation: 4,
		},
		employeeHeader: {
			flexDirection: "row",
			alignItems: "center",
			padding: 16,
		},
		employeeMainInfo: {
			flex: 1,
			flexDirection: "row",
			alignItems: "center",
		},
		employeeAvatarContainer: {
			width: 48,
			height: 48,
			borderRadius: 24,
			backgroundColor: theme.colors.accentSubtle,
			alignItems: "center",
			justifyContent: "center",
			marginRight: 16,
		},
		inactiveAvatar: {
			backgroundColor: theme.colors.border,
		},
		avatarText: {
			fontSize: 18,
			fontWeight: "600",
			color: theme.colors.accent,
		},
		employeeInfo: {
			flex: 1,
		},
		employeeName: {
			fontSize: 16,
			fontWeight: "600",
			color: theme.colors.text,
		},
		employeeRole: {
			fontSize: 14,
			color: theme.colors.textSecondary,
			marginTop: 2,
		},
		headerRight: {
			flexDirection: "row",
			alignItems: "center",
		},
		privilegeBadge: {
			paddingVertical: 4,
			paddingHorizontal: 8,
			borderRadius: 12,
			alignItems: "center",
			justifyContent: "center",
		},
		privilegeText: {
			fontSize: 12,
			fontWeight: "500",
		},
		expandedContent: {
			padding: 16,
			borderTopWidth: 1,
			borderTopColor: theme.colors.border,
		},
		detailRow: {
			flexDirection: "row",
			alignItems: "center",
			marginBottom: 12,
		},
		detailIcon: {
			marginRight: 12,
			width: 22,
		},
		detailText: {
			fontSize: 15,
			color: theme.colors.textSecondary,
			flex: 1,
		},
		accessButton: {
			flexDirection: "row",
			alignItems: "center",
			alignSelf: "flex-start",
			paddingVertical: 6,
			paddingHorizontal: 10,
			borderRadius: 8,
			backgroundColor: theme.colors.accentSubtle,
			marginTop: 4,
		},
		accessButtonText: {
			fontSize: 13,
			fontWeight: "600",
			color: theme.colors.accent,
			marginLeft: 6,
		},
		modalBackdrop: {
			flex: 1,
			backgroundColor: "rgba(0,0,0,0.4)",
			justifyContent: "flex-end",
		},
		modalSheet: {
			backgroundColor: theme.colors.surface,
			borderTopLeftRadius: 16,
			borderTopRightRadius: 16,
			padding: 20,
			paddingBottom: 34,
		},
		modalHeader: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			marginBottom: 16,
		},
		modalTitle: {
			fontSize: 18,
			fontWeight: "700",
			color: theme.colors.text,
			flex: 1,
			paddingRight: 12,
		},
		modalRow: {
			flexDirection: "row",
			alignItems: "center",
			paddingVertical: 12,
			borderBottomWidth: StyleSheet.hairlineWidth,
			borderBottomColor: theme.colors.border,
		},
		modalRowTitle: {
			fontSize: 15,
			fontWeight: "600",
			color: theme.colors.text,
		},
		modalRowHint: {
			fontSize: 13,
			color: theme.colors.textSecondary,
			marginTop: 2,
			lineHeight: 18,
		},
		modalSectionTitle: {
			fontSize: 13,
			fontWeight: "700",
			color: theme.colors.textTertiary,
			textTransform: "uppercase",
			marginTop: 18,
			marginBottom: 6,
		},
		modalEmpty: {
			fontSize: 14,
			color: theme.colors.textTertiary,
			paddingVertical: 10,
		},
		modalCheckRow: {
			flexDirection: "row",
			alignItems: "center",
			paddingVertical: 10,
		},
		modalCheckLabel: {
			fontSize: 15,
			color: theme.colors.text,
			marginLeft: 10,
			flex: 1,
		},
		modalWarning: {
			fontSize: 13,
			color: theme.colors.warning,
			backgroundColor: theme.colors.warningSubtle,
			padding: 10,
			borderRadius: 8,
			marginTop: 12,
			lineHeight: 18,
		},
		modalSave: {
			backgroundColor: theme.colors.accent,
			borderRadius: 10,
			paddingVertical: 14,
			alignItems: "center",
			marginTop: 20,
		},
		modalSaveText: {
			color: theme.colors.surface,
			fontSize: 16,
			fontWeight: "600",
		},
		notesContainer: {
			backgroundColor: theme.colors.surfaceSunken,
			padding: 12,
			borderRadius: 8,
			marginTop: 8,
		},
		notesTitle: {
			fontSize: 14,
			fontWeight: "600",
			color: theme.colors.textSecondary,
			marginBottom: 4,
		},
		notesText: {
			fontSize: 14,
			color: theme.colors.textSecondary,
			lineHeight: 20,
		},
		emptyContainer: {
			alignItems: "center",
			justifyContent: "center",
			padding: 40,
		},
		emptyText: {
			fontSize: 16,
			color: theme.colors.textTertiary,
			marginTop: 12,
		},
	});
