import { StyleSheet } from "react-native";

/** Presentation only — extracted verbatim from EmployeeList.tsx. */
export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#f8f9fa",
	},
	header: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 16,
		paddingVertical: 12,
		backgroundColor: "white",
		borderBottomWidth: 1,
		borderBottomColor: "#e1e4e8",
	},
	headerTitle: {
		fontSize: 18,
		fontWeight: "600",
		color: "#333",
		textAlign: "center",
		flex: 1,
	},
	backButton: {
		padding: 8,
	},
	subHeader: {
		backgroundColor: "white",
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderBottomWidth: 1,
		borderBottomColor: "#e1e4e8",
	},
	statsContainer: {
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	statItem: {
		alignItems: "center",
		paddingHorizontal: 24,
	},
	statValue: {
		fontSize: 22,
		fontWeight: "700",
		color: "#2089dc",
	},
	statLabel: {
		fontSize: 14,
		color: "#666",
		marginTop: 4,
	},
	statDivider: {
		height: 30,
		width: 1,
		backgroundColor: "#e0e0e0",
	},
	listContent: {
		padding: 16,
		paddingBottom: 24,
	},
	employeeCard: {
		backgroundColor: "white",
		borderRadius: 12,
		marginBottom: 12,
		overflow: "hidden",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 2,
		elevation: 2,
	},
	employeeCardExpanded: {
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.15,
		shadowRadius: 4,
		elevation: 4,
	},
	employeeHeader: {
		flexDirection: "row",
		alignItems: "center",
		padding: 16,
	},
	employeeMainInfo: {
		flex: 1,
		flexDirection: "row",
		alignItems: "center",
	},
	employeeAvatarContainer: {
		width: 48,
		height: 48,
		borderRadius: 24,
		backgroundColor: "#e6f2ff",
		alignItems: "center",
		justifyContent: "center",
		marginRight: 16,
	},
	inactiveAvatar: {
		backgroundColor: "#f0f0f0",
	},
	avatarText: {
		fontSize: 18,
		fontWeight: "600",
		color: "#2089dc",
	},
	employeeInfo: {
		flex: 1,
	},
	employeeName: {
		fontSize: 16,
		fontWeight: "600",
		color: "#333",
	},
	employeeRole: {
		fontSize: 14,
		color: "#666",
		marginTop: 2,
	},
	headerRight: {
		flexDirection: "row",
		alignItems: "center",
	},
	privilegeBadge: {
		paddingVertical: 4,
		paddingHorizontal: 8,
		borderRadius: 12,
		alignItems: "center",
		justifyContent: "center",
	},
	privilegeText: {
		fontSize: 12,
		fontWeight: "500",
	},
	expandedContent: {
		padding: 16,
		borderTopWidth: 1,
		borderTopColor: "#f0f0f0",
	},
	detailRow: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 12,
	},
	detailIcon: {
		marginRight: 12,
		width: 22,
	},
	detailText: {
		fontSize: 15,
		color: "#444",
		flex: 1,
	},
	accessButton: {
		flexDirection: "row",
		alignItems: "center",
		alignSelf: "flex-start",
		paddingVertical: 6,
		paddingHorizontal: 10,
		borderRadius: 8,
		backgroundColor: "#eaf4ff",
		marginTop: 4,
	},
	accessButtonText: {
		fontSize: 13,
		fontWeight: "600",
		color: "#2078c8",
		marginLeft: 6,
	},
	modalBackdrop: {
		flex: 1,
		backgroundColor: "rgba(0,0,0,0.4)",
		justifyContent: "flex-end",
	},
	modalSheet: {
		backgroundColor: "#fff",
		borderTopLeftRadius: 16,
		borderTopRightRadius: 16,
		padding: 20,
		paddingBottom: 34,
	},
	modalHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		marginBottom: 16,
	},
	modalTitle: {
		fontSize: 18,
		fontWeight: "700",
		color: "#222",
		flex: 1,
		paddingRight: 12,
	},
	modalRow: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 12,
		borderBottomWidth: StyleSheet.hairlineWidth,
		borderBottomColor: "#e5e5e5",
	},
	modalRowTitle: {
		fontSize: 15,
		fontWeight: "600",
		color: "#222",
	},
	modalRowHint: {
		fontSize: 13,
		color: "#777",
		marginTop: 2,
		lineHeight: 18,
	},
	modalSectionTitle: {
		fontSize: 13,
		fontWeight: "700",
		color: "#888",
		textTransform: "uppercase",
		marginTop: 18,
		marginBottom: 6,
	},
	modalEmpty: {
		fontSize: 14,
		color: "#999",
		paddingVertical: 10,
	},
	modalCheckRow: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 10,
	},
	modalCheckLabel: {
		fontSize: 15,
		color: "#333",
		marginLeft: 10,
		flex: 1,
	},
	modalWarning: {
		fontSize: 13,
		color: "#b26a00",
		backgroundColor: "#fff5e0",
		padding: 10,
		borderRadius: 8,
		marginTop: 12,
		lineHeight: 18,
	},
	modalSave: {
		backgroundColor: "#2078c8",
		borderRadius: 10,
		paddingVertical: 14,
		alignItems: "center",
		marginTop: 20,
	},
	modalSaveText: {
		color: "#fff",
		fontSize: 16,
		fontWeight: "600",
	},
	notesContainer: {
		backgroundColor: "#f9f9f9",
		padding: 12,
		borderRadius: 8,
		marginTop: 8,
	},
	notesTitle: {
		fontSize: 14,
		fontWeight: "600",
		color: "#555",
		marginBottom: 4,
	},
	notesText: {
		fontSize: 14,
		color: "#666",
		lineHeight: 20,
	},
	emptyContainer: {
		alignItems: "center",
		justifyContent: "center",
		padding: 40,
	},
	emptyText: {
		fontSize: 16,
		color: "#888",
		marginTop: 12,
	},
});
