import { StyleSheet } from "react-native";

/** Presentation only — extracted verbatim from PackageCreator.tsx. */
export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#f5f5f5",
	},
	header: {
		padding: 15,
		backgroundColor: "#fff",
		borderBottomWidth: 1,
		borderBottomColor: "#e0e0e0",
	},
	headerRow: {
		flexDirection: "row",
		alignItems: "center",
	},
	backButton: {
		padding: 5,
		marginRight: 10,
	},
	headerTextContainer: {
		flex: 1,
	},
	headerTitle: {
		fontSize: 24,
		fontWeight: "bold",
		color: "#333",
	},
	headerSubtitle: {
		fontSize: 16,
		color: "#666",
		marginTop: 5,
	},
	loadingContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	loadingText: {
		marginTop: 10,
		fontSize: 16,
		color: "#666",
	},
	listContainer: {
		flex: 1,
	},
	listContent: {
		padding: 15,
	},
	emptyContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingBottom: 100,
	},
	emptyText: {
		fontSize: 18,
		color: "#666",
		marginTop: 10,
	},
	emptySubtext: {
		fontSize: 14,
		color: "#999",
		marginTop: 5,
		textAlign: "center",
	},
	packageCard: {
		backgroundColor: "#fff",
		borderRadius: 8,
		padding: 15,
		marginBottom: 15,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 3,
		elevation: 2,
	},
	packageHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 10,
	},
	packageTitle: {
		fontSize: 18,
		fontWeight: "bold",
		color: "#333",
		flex: 1,
	},
	checklistCount: {
		fontSize: 14,
		color: "#666",
		backgroundColor: "#f0f0f0",
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 12,
	},
	packageDescription: {
		fontSize: 14,
		color: "#666",
		marginBottom: 15,
	},
	packageChecklists: {
		marginBottom: 15,
	},
	packageChecklistItem: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 5,
	},
	checklistIcon: {
		marginRight: 8,
	},
	packageChecklistTitle: {
		fontSize: 14,
		color: "#333",
	},
	moreChecklists: {
		fontSize: 14,
		color: "#888",
		marginTop: 5,
		fontStyle: "italic",
	},
	packageActions: {
		flexDirection: "row",
		borderTopWidth: 1,
		borderTopColor: "#f0f0f0",
		paddingTop: 10,
		marginTop: 5,
	},
	actionButton: {
		flex: 1,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 8,
	},
	actionText: {
		marginLeft: 5,
		fontSize: 14,
		color: "#333",
	},
	footer: {
		padding: 15,
		backgroundColor: "#fff",
		borderTopWidth: 1,
		borderTopColor: "#e0e0e0",
	},
	editorFooter: {
		padding: 15,
		backgroundColor: "#fff",
		borderTopWidth: 1,
		borderTopColor: "#e0e0e0",
		flexDirection: "row",
	},
	createButton: {
		backgroundColor: "#4CAF50",
		borderRadius: 8,
		padding: 15,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
	},
	createButtonText: {
		color: "#fff",
		fontSize: 16,
		fontWeight: "bold",
		marginLeft: 8,
	},
	editorContainer: {
		flex: 1,
	},
	formGroup: {
		margin: 15,
		marginBottom: 20,
	},
	label: {
		fontSize: 16,
		fontWeight: "bold",
		color: "#333",
		marginBottom: 8,
	},
	sectionDescription: {
		fontSize: 14,
		color: "#666",
		marginBottom: 15,
	},
	input: {
		backgroundColor: "#fff",
		borderWidth: 1,
		borderColor: "#ddd",
		borderRadius: 8,
		padding: 12,
		fontSize: 16,
	},
	textArea: {
		minHeight: 100,
		textAlignVertical: "top",
	},
	checklistSelectionContainer: {
		backgroundColor: "#fff",
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#ddd",
		overflow: "hidden",
	},
	checklistSelectionItem: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		padding: 15,
		borderBottomWidth: 1,
		borderBottomColor: "#eee",
		backgroundColor: "#fff",
	},
	checklistSelectionContent: {
		flex: 1,
	},
	checklistSelectionTitle: {
		fontSize: 16,
		color: "#333",
		marginBottom: 4,
	},
	checklistSelectionCount: {
		fontSize: 14,
		color: "#666",
	},
	noChecklistsContainer: {
		alignItems: "center",
		justifyContent: "center",
		padding: 30,
		backgroundColor: "#f9f9f9",
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#ddd",
		borderStyle: "dashed",
	},
	noChecklistsText: {
		fontSize: 16,
		color: "#666",
		marginVertical: 10,
		textAlign: "center",
	},
	createChecklistButton: {
		backgroundColor: "#2196F3",
		paddingHorizontal: 15,
		paddingVertical: 10,
		borderRadius: 4,
		marginTop: 10,
	},
	createChecklistButtonText: {
		color: "#fff",
		fontWeight: "bold",
	},
	selectedChecklistsContainer: {
		margin: 15,
		marginTop: 0,
		padding: 15,
		backgroundColor: "#f0f7f0",
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#c8e6c9",
	},
	selectedChecklistsTitle: {
		fontSize: 16,
		fontWeight: "bold",
		color: "#2E7D32",
		marginBottom: 10,
	},
	selectedChecklistItem: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 8,
		borderBottomWidth: 1,
		borderBottomColor: "#c8e6c9",
	},
	selectedChecklistTitle: {
		marginLeft: 10,
		fontSize: 15,
		color: "#333",
	},
	saveButton: {
		flex: 2,
		backgroundColor: "#2196F3",
		borderRadius: 8,
		padding: 15,
		alignItems: "center",
		justifyContent: "center",
	},
	saveButtonText: {
		color: "#fff",
		fontSize: 16,
		fontWeight: "bold",
	},
	cancelButton: {
		flex: 1,
		borderWidth: 1,
		borderColor: "#ddd",
		borderRadius: 8,
		padding: 15,
		alignItems: "center",
		justifyContent: "center",
		marginRight: 10,
		backgroundColor: "#f5f5f5",
	},
	cancelButtonText: {
		color: "#333",
		fontSize: 16,
		fontWeight: "500",
	},
});
