import { StyleSheet } from "react-native";
import { Theme } from "../../../theme";

/** Presentation only — extracted verbatim from PackageCreator.tsx. */
export const packageStyles = (theme: Theme) =>
	StyleSheet.create({
		container: {
			flex: 1,
			backgroundColor: theme.colors.surfaceSunken,
		},
		header: {
			padding: 15,
			backgroundColor: theme.colors.surface,
			borderBottomWidth: 1,
			borderBottomColor: theme.colors.border,
		},
		headerRow: {
			flexDirection: "row",
			alignItems: "center",
		},
		backButton: {
			padding: 5,
			marginRight: 10,
		},
		headerTextContainer: {
			flex: 1,
		},
		headerTitle: {
			fontSize: 24,
			fontWeight: "bold",
			color: theme.colors.text,
		},
		headerSubtitle: {
			fontSize: 16,
			color: theme.colors.textSecondary,
			marginTop: 5,
		},
		loadingContainer: {
			flex: 1,
			justifyContent: "center",
			alignItems: "center",
		},
		loadingText: {
			marginTop: 10,
			fontSize: 16,
			color: theme.colors.textSecondary,
		},
		listContainer: {
			flex: 1,
		},
		listContent: {
			padding: 15,
		},
		emptyContainer: {
			flex: 1,
			justifyContent: "center",
			alignItems: "center",
			paddingBottom: 100,
		},
		emptyText: {
			fontSize: 18,
			color: theme.colors.textSecondary,
			marginTop: 10,
		},
		emptySubtext: {
			fontSize: 14,
			color: theme.colors.textTertiary,
			marginTop: 5,
			textAlign: "center",
		},
		packageCard: {
			backgroundColor: theme.colors.surface,
			borderRadius: 8,
			padding: 15,
			marginBottom: 15,
			shadowColor: theme.colors.shadow,
			shadowOffset: { width: 0, height: 1 },
			shadowOpacity: 0.1,
			shadowRadius: 3,
			elevation: 2,
		},
		packageHeader: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			marginBottom: 10,
		},
		packageTitle: {
			fontSize: 18,
			fontWeight: "bold",
			color: theme.colors.text,
			flex: 1,
		},
		checklistCount: {
			fontSize: 14,
			color: theme.colors.textSecondary,
			backgroundColor: theme.colors.border,
			paddingHorizontal: 8,
			paddingVertical: 4,
			borderRadius: 12,
		},
		packageDescription: {
			fontSize: 14,
			color: theme.colors.textSecondary,
			marginBottom: 15,
		},
		packageChecklists: {
			marginBottom: 15,
		},
		packageChecklistItem: {
			flexDirection: "row",
			alignItems: "center",
			marginBottom: 5,
		},
		checklistIcon: {
			marginRight: 8,
		},
		packageChecklistTitle: {
			fontSize: 14,
			color: theme.colors.text,
		},
		moreChecklists: {
			fontSize: 14,
			color: theme.colors.textTertiary,
			marginTop: 5,
			fontStyle: "italic",
		},
		packageActions: {
			flexDirection: "row",
			borderTopWidth: 1,
			borderTopColor: theme.colors.border,
			paddingTop: 10,
			marginTop: 5,
		},
		actionButton: {
			flex: 1,
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			padding: 8,
		},
		actionText: {
			marginLeft: 5,
			fontSize: 14,
			color: theme.colors.text,
		},
		footer: {
			padding: 15,
			backgroundColor: theme.colors.surface,
			borderTopWidth: 1,
			borderTopColor: theme.colors.border,
		},
		editorFooter: {
			padding: 15,
			backgroundColor: theme.colors.surface,
			borderTopWidth: 1,
			borderTopColor: theme.colors.border,
			flexDirection: "row",
		},
		createButton: {
			backgroundColor: theme.colors.success,
			borderRadius: 8,
			padding: 15,
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
		},
		createButtonText: {
			color: theme.colors.surface,
			fontSize: 16,
			fontWeight: "bold",
			marginLeft: 8,
		},
		editorContainer: {
			flex: 1,
		},
		formGroup: {
			margin: 15,
			marginBottom: 20,
		},
		label: {
			fontSize: 16,
			fontWeight: "bold",
			color: theme.colors.text,
			marginBottom: 8,
		},
		sectionDescription: {
			fontSize: 14,
			color: theme.colors.textSecondary,
			marginBottom: 15,
		},
		input: {
			backgroundColor: theme.colors.surface,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			padding: 12,
			fontSize: 16,
		},
		textArea: {
			minHeight: 100,
			textAlignVertical: "top",
		},
		checklistSelectionContainer: {
			backgroundColor: theme.colors.surface,
			borderRadius: 8,
			borderWidth: 1,
			borderColor: theme.colors.border,
			overflow: "hidden",
		},
		checklistSelectionItem: {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "center",
			padding: 15,
			borderBottomWidth: 1,
			borderBottomColor: theme.colors.border,
			backgroundColor: theme.colors.surface,
		},
		checklistSelectionContent: {
			flex: 1,
		},
		checklistSelectionTitle: {
			fontSize: 16,
			color: theme.colors.text,
			marginBottom: 4,
		},
		checklistSelectionCount: {
			fontSize: 14,
			color: theme.colors.textSecondary,
		},
		noChecklistsContainer: {
			alignItems: "center",
			justifyContent: "center",
			padding: 30,
			backgroundColor: theme.colors.surfaceSunken,
			borderRadius: 8,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderStyle: "dashed",
		},
		noChecklistsText: {
			fontSize: 16,
			color: theme.colors.textSecondary,
			marginVertical: 10,
			textAlign: "center",
		},
		createChecklistButton: {
			backgroundColor: theme.colors.accent,
			paddingHorizontal: 15,
			paddingVertical: 10,
			borderRadius: 4,
			marginTop: 10,
		},
		createChecklistButtonText: {
			color: theme.colors.surface,
			fontWeight: "bold",
		},
		selectedChecklistsContainer: {
			margin: 15,
			marginTop: 0,
			padding: 15,
			backgroundColor: theme.colors.successSubtle,
			borderRadius: 8,
			borderWidth: 1,
			borderColor: theme.colors.success,
		},
		selectedChecklistsTitle: {
			fontSize: 16,
			fontWeight: "bold",
			color: theme.colors.success,
			marginBottom: 10,
		},
		selectedChecklistItem: {
			flexDirection: "row",
			alignItems: "center",
			paddingVertical: 8,
			borderBottomWidth: 1,
			borderBottomColor: theme.colors.success,
		},
		selectedChecklistTitle: {
			marginLeft: 10,
			fontSize: 15,
			color: theme.colors.text,
		},
		saveButton: {
			flex: 2,
			backgroundColor: theme.colors.accent,
			borderRadius: 8,
			padding: 15,
			alignItems: "center",
			justifyContent: "center",
		},
		saveButtonText: {
			color: theme.colors.surface,
			fontSize: 16,
			fontWeight: "bold",
		},
		cancelButton: {
			flex: 1,
			borderWidth: 1,
			borderColor: theme.colors.border,
			borderRadius: 8,
			padding: 15,
			alignItems: "center",
			justifyContent: "center",
			marginRight: 10,
			backgroundColor: theme.colors.surfaceSunken,
		},
		cancelButtonText: {
			color: theme.colors.text,
			fontSize: 16,
			fontWeight: "500",
		},
	});
